### ISSUE TITLE
It's all about relationships: Keeping your data model simpler, more reusable, and powerful

### ISSUE THREAD

**Issue by allanwhite** [contentful/contribution-program#11]
We use Related entry types pretty heavily for our implementation of Contentful that drives [datica.com](datica.com). I made a decision early on to make a clear distinction between "article/page" type entries (larger pieces of content that have a fixed URL) and "related bits" that plug into those larger pieces, that represent fundamental reusable entities. These types include:

- Calls to action (CTAs). These can be associated with any entry, and have some complex variable features themselves.
- Forms and Scripts. These are used like CTAs, but for embedding our Hubspot forms (though can be used in other ways too).
- People. These are probably the most heavily-used related content type, and is used for everything from our company leadership directory to customer profiles to guest authors.
- Products/services and features.
- Tags which are used for search and SEO purposes.
- Quotes are related to people, customers, landing pages, and even used for press quotes.

These all get plugged into more typical data types like blog posts, documentation-like articles, landing pages with downloads, customer case studies, etc. 

One of the reasons I pitched Contentful to our young startup company was so that our public content strategy would live separately and beyond the website, and allow us to adapt it to our needs as we grow. In this proposed post, I'd take a look at each related type and examine how they're used today and also how it could be used in the future. I might also make a few Contentful suggestions or questions for how these underlying requirements might make them more useful in the future.

**Comment by stefanjudis** [comment]
Hey Allan. 👋 Thanks for submitting this idea. :)

I also really like this one – in case you wanna move it to [the editorial pipeline](https://github.com/contentful/contribution-program/projects/1) let me know. :)

**Comment by allanwhite** [comment]
@stefanjudis Do it!

**Comment by stefanjudis** [comment]
Wooohooo. Great! Done. 🎉

If you could provide us with [an outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) before starting to write we could give feedback and share ideas! :)

**Comment by allanwhite** [comment]
## Outline

- Introduction: In this post, I'll look at how we identified these data types, and leveraged the Related Entries features of Contentful for running our marketing site, Datica.com.
- Elegance: between complexity and power
- Assessing your content model. How did we go about deciding which fields to make referenced fields, and which to remain as part of the core entry?
  - Example: A Blog Entry. Table of fields and explanations.
- A list of our “Metadata bits”
  - **Calls to action (CTAs).** These can be associated with any entry, and have some complex variable features themselves.
  - **Forms and Scripts.** These are used like CTAs, but for embedding our Hubspot forms (though can be used in other ways too).
  - **People.** These are probably the most heavily-used related content type, and is used for everything from our company leadership directory to customer profiles to guest authors.
  - **Products/services** and features.
  - **Tags** which are used for search and SEO purposes.
  - **Events** are talks, meetups, tradeshows, or webinars. 
  - **Quotes** are related to people, customers, landing pages, and even used for press quotes.
- Bulletproofing your related content and workflow. This gets into governance, training, and design. 
- Future related content work: handling some more complex models.

# Rough Entry Draft: It's all about relationships: Keeping your data model simpler, more reusable, and powerful

---

When envisioning your content for a marketing website (or really, any web project) it's useful to visualize your _entity types_ before getting started. “Entities” are a fancy way of saying, “types of things”. What are the main bits of content that are unique? What other  types are reusable (for example, blog authors or people in general)? In this post, I'll look at how we identified these data types, and leveraged the Related Entries features of Contentful for running our marketing site, Datica.com.

## Elegance: between complexity and power

The universe of programming contains some helpful concepts that are useful for achieving one of my favorite adjectives: _elegance_. Elegance, for me, represents a pleasing balance between complexity and power. It’s tempting to go crazy with a feature like Related Entries—but this can increase complexity and make things harder to manage. 

In my career, I’m usually building a site for someone else: a marketing team or other group who is producing content using the publishing tools I’m building. Often, we’re not the ones _using_ the CMS; a complex workflow or deeply nested content model can easily confuse the ones doing the publishing. 

I find that when it comes to content modeling, it’s best not to over-plan at the beginning, but take a more iterative approach. There are usually some obvious types of things (i.e. entities or content types) that make sense as related types, like blog authors or call-to-action banners. Starting with a basic set of fields and adding on as you go vastly simplifies the work rendering that content in your templating system.

## Assessing your content model

### Example: A Blog Entry

In this example, we examine a blog entry, which has both regular and related fields. (picture of [blog entry example](https://datica.com/blog/mapping-digital-health-dr-ethan-bechtel-ohmd/))

Field Name | Type
-----|-----
Title | Short text
Slug | Short text
Publish Date | Date & time
Tags | References, many
Categories, Blog | Short text
Author | Reference
Featured Image | Media
Social Share Image | Media
Summary | Long text
Lead | Long text
Featured Person | Reference
Main Entry | Long text
Call to Action | Reference
Related Entries | References, many
Discovery Topic | Reference

How did we go about deciding which fields to make referenced fields, and which to remain as part of the core entry? **Reusability**, **scalability**, and **development costs** are the primary considerations when planning related entries. It’s really tempting to go crazy and add lots of custom fields and related fields. These all come with a cost in development time, and content training and management. 

Questions I ask myself and the team I’m building the system for: 

- How common would this related entry be across all entries of a given type? Of other types? Authors, for example, are a near-universal entity type across blog entries. A related product or service might be fairly rare. 
- How unique to this parent entry or type is the proposed related type? Is it going to be used _only_ with say, a blog entry, or is it useful in many places? Quotes were an early entity type that were intended to be associated in lots of places and with many other content types—product pages, customer case studies, etc. I actually got into a bit of trouble with this one when it came to the Customer data model, where Case Study entries contain Customers who contain Quotes… which one gets displayed? It was a bit of a mess on the template side. Don’t be too slick!

## A list of our “Metadata bits”

Here’s a few key related entry types that we ended up with and have proven their usefulness:

- **Calls to action (CTAs).** These can be associated with any entry, and have some complex variable features themselves.
- **Forms and Scripts.** These are used like CTAs, but for embedding our Hubspot forms (though can be used in other ways too).
- **People.** These are probably the most heavily-used related content type, and is used for everything from our company leadership directory to customer profiles to guest authors.
- **Products/services** and features.
- **Tags** which are used for search and SEO purposes.
- **Events** are talks, meetups, tradeshows, or webinars. 
- **Quotes** are related to people, customers, landing pages, and even used for press quotes.

_I’d show a few screenshots of these design patterns to show how they look when rendered_. 

## Bulletproofing your related content

If you relate something, you must consider what that piece of content looks like when rendered. A button? A simple link? A card, with an image preview and other related metadata? What are your fallback and content truncation rules? Some of these problems are managed through content governance, like limiting the length of text fields, or helpful help and error text (all of which happens on the Contentful side, in this case). Other aspects of bulletproofing your related content must happen on the template side. In the process of learning Ruby ERB and now, Slim templating for our Middleman static site, I discovered early on that not checking for the presence of fields would break the entire static site build. 

I learned early in my career that content authors cannot see or envision these limitations—they need us to train them and the “system” that we build for them to handle missing fields, too-large images, or content gaps elegantly with a minimum of fuss. 

## Future related content work

We have some fairly complex data models involving our [Digital Health Success Framework](datica.com/dhsf) (can provide screenshots and animations for inline content). Right now, that’s managed using hand-written Yaml data files. It was such a new concept (layered timelines, complex interactions, lots of little metadata bits on each entry, etc.) that we didn’t know what would be needed at first. It being a new experimental concept also meant we didn’t know if it would take off or not—no sense overbuilding a web product that’s one-and-done. After a few months, the design & data model iterations had slowed and the data model stabilized. The pace of updates (we added a new layer or dimension, and the time scale changed) also fell into a pattern that we could predict.

When evaluating how much effort to put into making content managed in a CMS, I ask questions such as:

- How often will this content need to be added or updated?
- How many different people need to be able to make these changes?
- What skill or subject expertise will authors need?
- How deeply does this content need to be integrated with other content? 

This last point is one that can be a real rabbit hole, sucking you into an inception-like world of complexity and frustration.

**Comment by robertsvensson** [comment]
@allanwhite Hey Allan, I'm Robert and I'll be your copy editor. Both the outline and the draft look very promissing. I'll move you forward to "draft in progress".

**Comment by robertsvensson** [comment]
Note to self: feature image ordered MD-97

**Comment by allanwhite** [comment]
@robertsvensson Hi Robert - am I waiting for you to edit copy, or do you need something from me? I plan on providing some graphics & screenshots to illustrate the components. Let me know here or on Contentful Slack - thanks.

**Comment by robertsvensson** [comment]
@allanwhite Hi Allan. I have everything I need from your side. Our editorial team will start working on the copy on Friday. Let me know when the graphics & screenshots are ready. Thanks!

**Comment by robertsvensson** [comment]
@allanwhite Hi Allan - have you had a chance to look at the gdoc I shared with you? Thanks!

**Comment by katchja** [comment]
@allanwhite My team is just starting to explore headless CMS for an app, which has components of ecommerce and content marketing. Hence, CTAs are important. We want to test them, experiment with very short, snappy offers and with long-form content - such as a story about how a product was done. 
We haven't started using Contentful, but from your post it seems it should be possible to edit, create and publish shorter entities with CTAs in the app, and get them to be rendered differently in app. Is it also easy to integrate analytics or are there too many layers of integrations? what's your opinion on this?

**Comment by Shy** [comment]
Hey folks, 

Since it looks like we haven't had any changes to this issue for a few months I'm going to close the ticket. I don't have full awareness of what's going on so if that's incorrect let me know and I'll open it back up.

**Comment by allanwhite** [comment]
@Shy Hi Shy - honestly I got pulled in different directions and kind of forgot about this project! I'll try and pick it up in the new year here. I may just publish it on my own and notify you for cross-publication.
