### ISSUE TITLE
Contentful for Designers and Front-Enders: What You Need To Know

### ISSUE THREAD

**Issue by allanwhite** [contentful/contribution-program#12]
As a designer, UX and front-end practitioner (aka a non-engineer), using Contentful to solve my business problem (building our new website) was definitely a tough technical challenge. For those evaluating Contentful for marketing/communication projects, I'd examine a few pros, cons, and considerations for non-developers. A few areas I might explore:

### What can I or my team do in-house?
Contentful is a developer-oriented product, which fortunately works with many different stacks. A marketing team that has mostly designers and not engineers might need to evaluate if they have the right dev skills in-house, or if they need to look outside their group or company for implementation. I had to learn Ruby fast when our in-house teams were re-assigned.

### What skills do we need to have to build on top of it?
In my particular case, I had to wrangle all our old content (hundreds of markdown posts) and import those to Contentful; learn how to use `middleman-contentful` to parse the new content; learn Ruby ERB to render the content in templates. I had key Ruby assistance but ongoing support was tough (startup life!). I've since learned how to do some more advanced queries and Slim templating, and things are pretty smooth. 

### What opportunities does it offer vs. other solutions?
I had a broader vision for content that might involve efforts like integrating it with internal tools (say, Salesforce) for generating instant targeted collateral; using it for onboarding content or even documentation in our CLI tools; and things like automated ebook generation. For now, running the marketing site alone is keeping us pretty busy, but the nature of Contentful as a platform to build on top of will enable flexibility in the future. 

### What's the cost/benefit angle look like to decision-makers?
The primary drivers of our decision were thus:

1. Free/low cost to start. There's a lot of capability for nearly no cost.
2. At the time, we had a lot of in-house Ruby experience, and we wanted to build on the Middleman static site generator. That there were existing bridges and use cases for that was a plus.
3. The integrated CDN and image attributes meant that didn't have to be done on the server side. Checked that box for us.
4. It could be a content platform we could build on top of as we grew, with its value growing over time as a repository for company-wide content. Future needs were fuzzy, but at least content wouldn't be "trapped" inside a monolithic CMS.

One thing I might unpack here is: this solution combination is low/near-zero cost—but you have to build it yourself. That's where the cost is. Now that our marketing team has grown and uses it regularly, we could use more workflow control, for example (maybe via UI extensions, or even other apps that talk to Contentful). 

The heart of this content post idea is: knowing oneself or one's team; what can I do myself or in-house? Do I/we have the right skills to make Contentful a fit for this problem? Or do I need something else?

**Comment by stefanjudis** [comment]
Hey Allan. 👋 Thanks for submitting this idea. :)

I would love to read this! If you wanna take it to the editorial board, we'd be happy to work with you on that. :)

**Comment by allanwhite** [comment]
@stefanjudis Notify me if this goes to the Pipeline, or let me know what needs to be done editing-wise. Thanks.

**Comment by stefanjudis** [comment]
Hey @allanwhite, sorry for the delay.

> The heart of this content post idea is: knowing oneself or one's team; what can I do myself or in-house? Do I/we have the right skills to make Contentful a fit for this problem? Or do I need something else?

I think this core is very useful!

I'm not really sure about "What's the cost/benefit angle look like to decision-makers?" because the points are rather technical and read like a feature list.

The first three points make complete sense to me. 👍 🎉

**Comment by stefanjudis** [comment]
@allanwhite Do we still plan to make this happen? can I help with anything?

**Comment by stefanjudis** [comment]
@allanwhite I'll close this for now. :) Happy to re-open in the future. :)

**Comment by stefanjudis** [comment]
@allanwhite I'll close this for now. :) Happy to re-open in the future. :)
