### ISSUE TITLE
Trends in Content Management

### ISSUE THREAD

**Issue by allanwhite** [contentful/contribution-program#13]
Looking at the proposals in this list here, it's clear to me that there's a lot happening (!) in this space. It would be interesting to get a bunch of different perspectives on what people are asking for, what kinds of business problems are involved, and how other CMSs approach them.

**Comment by gauravwadekar** [comment]
Hi Allan

I am working on a project where I work very closely with editors, publishers and how the content is managed at our organization. 

I think customer centered content is key and writing it for the identified audience requires a content management system which supports this concept.

And there is integration with social media which generally forms an important aspect of content strategy at large organizations.

Let me know what you think about a topic on these lines and I can start putting a structure together for this.

Regards
Gaurav
LinkedIn: https://www.linkedin.com/in/wadekargaurav/
