### ISSUE TITLE
What are the top feature requests from Contentful users?

### ISSUE THREAD

**Issue by allanwhite** [contentful/contribution-program#14]
I know I have a wish list, what are others asking for? What are some that might or might not align with Contentful's roadmap or business model?

**Comment by stefanjudis** [comment]
I second that it's useful to know what others are asking for. I think though, that a blog post may no be the perfect medium for this content.

https://www.contentfulcommunity.com/ might be a better place? There are e.g. [discussions going into this direction](https://www.contentfulcommunity.com/t/what-contentful-integrations-would-you-love-to-see-us-build/822).

**Comment by allanwhite** [comment]
Great point @stefanjudis - maybe an idea for you later, to curate those or have some kind of round table format for a blog post. "hot ideas from the community" or whatever.
