### ISSUE TITLE
Building a static portfolio site with Contentful, Next.js and Netlify

### ISSUE THREAD

**Issue by tomsansome** [contentful/contribution-program#15]
This began as a talk at the London Contentful Dev Meetup on 10th April.

I recently re-built my portfolio to be a static site using Contentful, Next.js and Netlify to produce something fast and easy to maintain.

This post will go from starting up a new project, to hosting, and even include using Contentful Webhooks and Netlify Build hooks to update content.

The original talk can be found here as slides – http://slides.com/sansometom/contentful-dev-meetup-april-10th. This will need to be adapted slightly which I have begun doing.

**Comment by robertsvensson** [comment]
This is a great idea. A Contentful / Netlify integration using webhooks is something I believe a lot readers will find interesting.

Do you already have a written draft somewhere?

**Comment by tomsansome** [comment]
Hey @robertsvensson – I have this draft here, which will need updating to have inline code blocks, not images of code 😆

...I was wondering before I go through and edit this, should I even bother with the code block swap, as I'm only going to have to type it up again on your platform (where I could do the swap from images of code to inline code blocks)?

Please say if I've not made any sense there.

https://medium.com/@tomsansome/building-a-portfolio-site-with-contentful-next-js-and-netlify-7db6ad67dee2

**Comment by robertsvensson** [comment]
hey @tomsansome — The draft looks very good.

It would be great if you could swap the images for code blocks in the Medium post, and then I'll copy all of it into our Contentful blog space.

**Comment by tomsansome** [comment]
@robertsvensson Ok great, I'll go ahead and do that on the post as soon as I can, I'll let you know on here when I'm done 👍 

Thanks!

**Comment by allanwhite** [comment]
Love this topic, I'm looking at this set of problems as well.

**Comment by tomsansome** [comment]
Great, hopefully this will help out in some way @allanwhite 😀

**Comment by robertsvensson** [comment]
Note to self: feature image ordered MD-95

**Comment by tomsansome** [comment]
Hi @robertsvensson, this post has been updated now – https://medium.com/@tomsansome/building-a-portfolio-site-with-contentful-next-js-and-netlify-7db6ad67dee2 👍

**Comment by bradsoo** [comment]
Hi @tomsansome I work with Robert and I've taken a look at your post.
It looks like your article would be better suited for publishing on dev.to. Our proposition is to publish onto dev.to first and then later make the post available on the Contentful blog and add you to the community page. Is this something you would be agreeable to? 

P.S. The contribution program is still very fresh out the gate and we're still working on the processes, so sorry that we're clear on the above from the start.

**Comment by tomsansome** [comment]
Hey @bradsoo – I got the first message you sent over before this was edited, and it mentioned publishing to dev.to, I know you have now taken that away but if you are not feeling confident about having the post on Contentful I am happy to take feedback you may have to improve it so that you are comfortable with it going on there, if that was the problem?

There has been nothing else that has been a problem on my end, I have watched the process unfold and it looks all good to me with using Github Projects as the pipeline for this, looks smooth to me 👍 

Let me know if there was something troubling you about the post which made you think it might not be suited to Contentful blog, thanks!

**Comment by tomsansome** [comment]
@bradsoo, happy to take comments/feedback over here if that's helpful to you – https://medium.com/@tomsansome/building-a-portfolio-site-with-contentful-next-js-and-netlify-7db6ad67dee2

**Comment by bradsoo** [comment]
@tomsansome Oh no, contrary to that - your article is great and we've got lots of confidence in it being posted on the blog. In fact, we're confident in it and want it to perform well; which is why the team decided to undo the change of course in my initial reply and go ahead with the initial plan.

Right now, we're looking at the possibility to expand article posting across different sites/publications, but need to evaluate performance of submissions to dev.to further (that's why we're opting to start submitting in-house works to dev.to first, and keeping community pieces on the tried-and-tested Contentful site).

**Comment by tomsansome** [comment]
@bradsoo ok that's great 👍 fully understood. I wanted to be open to feedback if needed, so thanks for explaining.

Looking forward to seeing the blog post up on the site, thanks for letting me know about that!

**Comment by bradsoo** [comment]
@tomsansome Sure, just to let you know, your article is now live on the blog: https://www.contentful.com/blog/2018/05/09/building-portfolio-website-contentful-nextjs-netlify/

Please have a look and let me know your thoughts. 
Also, the article is a bit heavy on screenshots (I counted 32) so I'm thinking of removing some images which explain some of the more obvious or simpler procedures.

**Comment by tomsansome** [comment]
@bradsoo, thanks for sending the link, this looks great! I'd agree with removing a few screenshots, that's fine by me!

I noticed a few things:
- Line 1 here needs a closing `'` - https://cl.ly/rS5d
- Very minor, could we add a little spacing here please? https://cl.ly/rSaT

...otherwise, I think it's all good.

Thanks again!

**Comment by bradsoo** [comment]
@tomsansome Cool, thanks. I've made the changes and removed 2 screenshots: the one with the blank package.json fiel and the one referencing the Next.js repo (replaced image with link instead).

Thank you again for your contribution!

**Comment by stefanjudis** [comment]
Clean up time. This was published and that for can be closed. :)
