### ISSUE TITLE
Building common.com with Contentful, Next.js, S3, and Slack

### ISSUE THREAD

**Issue by ldthorne** [contentful/contribution-program#18]
Hi there, I've been thinking of writing about how my team built [common.com](https://www.common.com), a static site powered by Contentful and Next.js, how we support our Content team in enabling them to iterate quickly, and what we've learned along the way. I'd love to get some guidance and feedback regarding what would be interesting to write about and how to approach it. Looking forward to speaking with someone at Contentful!

Cheers,

Daniel

**Comment by stefanjudis** [comment]
@ldthorne 

Hey Daniel,

this sounds great! First thing is to provide [an outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) (GDoc would be great but we can work with whatever works best for you). A well structured outline gives you and us a better feeling of what you want to say. The core of a good article follows a narrative. :)

> how we built a static site powered by Contentful and Next.js, how we support our Content team in enabling them to iterate quickly, and what we've learned along the way.

For me all of these three topics work well! 🎉 The Contentful + Next part [was covered recently](https://www.contentful.com/blog/2018/05/09/building-portfolio-website-contentful-nextjs-netlify/) meaning that when you're following the same approach as Tom I'd rather reference the article than doubling the content. If you do things a little differently though – I think there is a lot of value in sharing this.

> and what we've learned along the way.

☝️ I think this is always a very important part. People can learn and relate to your experience. :)

Looking forward to your outline and if you have any questions let me know. :)

**Comment by stefanjudis** [comment]
Hey @ldthorne, 👋🏻

how's life? :) Do you need anything from my side? Let me know if I can help somehow. :)

**Comment by stefanjudis** [comment]
Closed due to inactivity. Happy to reopen in the future. :)
