### ISSUE TITLE
Faster boot up times for static sites with Rollup

### ISSUE THREAD

**Issue by jeremenichelli** [contentful/contribution-program#19]
Hi there!

I have this already completed draft about bundlers and how Rollup might be a better fit for static sites. I don't know if it fits the topics that are expected room this Contribution Program, if that's the case I'm more than OK to post it somewhere else, but first I wanted to check if you are interested on hosting it.

Gist draft: https://gist.github.com/jeremenichelli/12c09cee1bc826b71e81ca3d3482f681

Let me know if the article is a fit on your blog 😊 Have a nice Friday!

**Comment by bradsoo** [comment]
Hi @jeremenichelli, I'm Brad, Technical Writer for Contentful. I'll be your editor for this project.

That looks like an excellent draft - I'll put this in a Google Doc so I can work on it with the team. Then we can move this along and get it up online as quickly as we can!

**Comment by jeremenichelli** [comment]
Awesome Brad, that sounds great considering I need new socks 😛

I'll be waiting for feedback in case there's need of some big rewrite or rephrasing. Thanks!

**Comment by bradsoo** [comment]
Hi @jeremenichelli, thanks for your draft and patience! I got to dive into what you've written earlier this week and have placed it in this GDoc with my edits and comments:

https://docs.google.com/document/d/1yHPUC3RuS75zsIkUwYuyj4H9Vpb1vGgTm-cnvm0OxC4

I've already ordered a feature image for your article and that's already been completed by our designer. So with your input and edits (and of course, your sign-off), we can publish your article as soon as this Friday!

**Comment by jeremenichelli** [comment]
Awesome @bradsoo, I just requested access to the draft so I can read the feedback and make corrections to the article if necessary.

**Comment by bradsoo** [comment]
@jeremenichelli I granted access earlier today (FYI). Thanks for the super fast responses too!

**Comment by jeremenichelli** [comment]
@bradsoo If we are not really in a hurry, I will like to try come up with a simple jekyll showcase to see if I get meaningful numbers to post in the article as Stefan suggested. What do you think?

**Comment by stefanjudis** [comment]
@jeremenichelli That sounds great and I'd love to see that! ❤️ 🤞🏻 👍🏻

**Comment by jeremenichelli** [comment]
We'll put some work around that over the weekend.

**Comment by bradsoo** [comment]
Sounds good, looking forward to seeing that!

**Comment by jeremenichelli** [comment]
Hi @bradsoo and @stefanjudis, I gave it a try this weekend and probably because of my sample snippets not being _heavy enough_ the results that I had were not conclusive to actual do a strong statement as I'm doing in this article.

So, currently I'm having a lot of second thoughts about releasing this. If some of you have an idea on how to shift the title or tone of the article to make it valuable I'm open for it.

Right now, I don't feel confortable releasing it and I wanna thank Stefan in advance for pointing this to me 💟 

I would actually suggest to close this issue since I don't know when I will have time to revisit this and rewrite, I have a busy conference and speaking season ahead.

Wanna hear your thoughts.

**Comment by stefanjudis** [comment]
@jeremenichelli 

We're not too tied to the static sites connection and would still love to publish the piece. :) 

So I think we could cut out the static sites connections here and there it'd be still a good piece. What do you think? 

Good luck with the conferences! ;)

**Comment by jeremenichelli** [comment]
Thanks for being open about the topics, the thing is that the whole purpose was to show how I was bundling the script on my static site avoiding usual bundlers overhead. If there's no measurable advantage I would need to shift the whole article axis of topic.

I'll need time to see if something comes to my mind. If any of you have any suggestion for a new direction the article can take I'm open to explore that.

**Comment by stefanjudis** [comment]
Ja, understood. :)

that's a bummer – but yeah, if we didn't come to the wished conclusions it's kinda missing the point. :(

I think for now we can close here then, but if you wanna write in the future let us know, @jeremenichelli . :)

**Comment by jeremenichelli** [comment]
Yeap, makes total sense.

Sorry for the noise, and thanks for the proofreading and recommendations.

**Comment by stefanjudis** [comment]
No worries. :)
