### ISSUE TITLE
Boost you Serverless backend with GraphQL and Prisma (formerly Graphcool)

### ISSUE THREAD

**Issue by mkorbi** [contentful/contribution-program#20]
I would like to write a blog article about building a Serverless based GraphQL implementation with the help of Graphcool. 

The article will be in a format of a walkthrough of using Graphcool to get your serverless GraphQL backend up & running, so it will allow you to get your own stuff implemented within no time.

**Comment by stefanjudis** [comment]
@mkorbi Hey Max,

this sounds great! I've got one question though. :) Didn't the folks from graphcool decide to go all in with prisma, now? Would writing about prisma be an option too?

Either way, i think it's good stuff though! 🎉

**Comment by mkorbi** [comment]
Yeah you are right. Prisma is the way to go :)

**Comment by stefanjudis** [comment]
@mkorbi Cool! Then let's do it. 🎉 

Next step would be to provide a planned outline (gist, gdoc, whatever works best for you) and then we can get this started. :)

**Comment by stefanjudis** [comment]
hey @mkorbi, anything I can help you with here? :)

**Comment by mkorbi** [comment]
@stefanjudis you can find the outline here https://gist.github.com/mkorbi/4961b132687b0149874ed5f50e713e49

**Comment by stefanjudis** [comment]
@mkorbi this looks great! I [moved your card into `draft in progress`](https://github.com/contentful/contribution-program/projects/1). :) I think we can roll with this. 🎉

If you need anything during the writing phase, let me know. :)

**Comment by stefanjudis** [comment]
@mkorbi Hey Max, how is it going? Can I help with anything here to move the project further? 

Have a great day!

**Comment by stefanjudis** [comment]
Max answered me that he needs a bit more time. :)

**Comment by stefanjudis** [comment]
hey @mkorbi. Just checking in. All good? :)

**Comment by mkorbi** [comment]
hi @stefanjudis unfortunately I can't finish this topi, because of a lack of time

**Comment by stefanjudis** [comment]
No worries. :)
