### ISSUE TITLE
Reposting articles on serverless and static sites

### ISSUE THREAD

**Issue by connor11528** [contentful/contribution-program#21]
Hi there,

I have a few articles on static sites and serverless that I'd like to repost as part of the Contentful contribution program. On the landing page it mentions $100 Amazon card for a repost. I'd be happy to make edits to the articles where necessary to provide the most value for our audience!

Static sites:
- Host a Vue.js website on Amazon S3 ([article link](https://medium.com/point-of-vue/host-a-vue-js-website-on-amazon-s3-for-the-best-hosting-solution-ever-%EF%B8%8F-eee2a28b2506))
- Launch a Website with a Custom URL using Github Pages and Google Domains ([article link](https://medium.com/employbl/launch-a-website-with-a-custom-url-using-github-pages-and-google-domains-3dd8d90cc33b))

Serverless:
- Tutorial for building a Web Application with Amazon S3, Lambda, DynamoDB and API Gateway ([article link](https://medium.com/employbl/tutorial-for-building-a-web-application-with-amazon-s3-lambda-dynamodb-and-api-gateway-6d3ddf77f15a))

Please let me know the process for moving forward

**Comment by stefanjudis** [comment]
Hey @connor11528,

thanks. :) The contribution reposts are meant for contentful related content. Sorry about the confusion. I updated the pages accordingly. :)

But if you write something about Contentful or publish on our blog initially we're happy to have a look. :)

**Comment by connor11528** [comment]
Okay awesome thanks for the clarification @stefanjudis makes sense!

I'll think up some articles to post on the contentful blog initially

**Comment by stefanjudis** [comment]
That sounds great! 👍🏻
