### ISSUE TITLE
GraphQL : Pros and Cons of Backends (REST, DBs, etc)

### ISSUE THREAD

**Issue by nicholashagen** [contentful/contribution-program#22]
I’d be interested in doing an article on showing the advantages and disadvantages of backing GraphQL with REST vs straight to the data tier, as well as showing how GraphQL fits into various tiers of an organization (data tier, product tier, etc)

**Comment by stefanjudis** [comment]
@nicholashagen We'd love to read more about this! :) 

Can you provide an outline so that we can discuss structure and your ideas?

Thanks! 🎉

**Comment by nicholashagen** [comment]
Thanks, for the interest.  Below is what I'm thinking for a general outline.


# Brief Overview
Short and sweet introduction to GraphQL, its history, purpose, and use.

## Purpose
Explain the purpose of GraphQL, where it fits and how it compares to other technologies such as REST or other traditional SOA architectures.

## Schemas
Explain the definition of GraphQL as expressed through schemas separate from the implementation details.  Explain the importance of this separation.  Explain the power and flexibility of schemas.

## Resolvers
Explain how schemas tie back to resolvers used to actually fetch and process the data.  Explain how each field can be associated with a resolver, how contexts and state work, and arguments.

# Methodologies
Continue the tying of resolvers and schemas and explain the high level idea of implementations and backing the underlying data with various architectures.

## REST
Showcase and explain the pros and cons of backing an existing REST-based architecture with GraphQL, where it fits, where it doesn't, and the possible pitfalls associated with it.  Explain the N+1 problem and solutions with respect to REST.

## DAO
Showcase and explain the pros and cons of putting GraphQL directly on top of data stores and DAO tiers, the performance advantages and flexibility, and the disadvantages as it relates to products and users and requirements.

## Binary Transports
Show how binary transports such as gRPC can be leveraged instead of REST to fetch data more efficiently.

## Composition 
Showcase how various composition-based libraries can composite multiple GraphQL backends together to back GraphQL by GraphQL and create relations between distinct GraphQL implementations.

# Three Tier Architecture
Finish off the documentation by showing how GraphQL fits cleanly into a standard three tier architecture, explaining each tier and its relation to GraphQL.

## GraphQL Cores
Show how the underlying data tier are composed of core focused data exposed through GraphQL for flexibility, power, and customization.

## GraphQL Products
Show how products and product-based requirements can tie together multiple distinct core-focused system into a single product for consumers showing how GraphQL can stitch various types of data together.

## Views
Explain how views use the product-focused tier to fetch the product-based data for their specific view, attach view logic to the data and output views accordingly.

# Conclusion

Tie everything back together with final opinions, thoughts, and how and when to choose one methodology over another.

**Comment by stefanjudis** [comment]
I wonder if this doesn't become too long for one article, but I think we could give it a shot? And have a look together when this progressed to a draft?

**Comment by nicholashagen** [comment]
Size was concerning yeah. We can probably remove the last three tier architecture article (probably better off as its own article anyways in future). The meat of the article should be in the methodologies section and everything else should be short blips. 

Just let me know next steps where you want to take this.

Thanks

**Comment by stefanjudis** [comment]
@nicholashagen I think you can start working on a draft and then we see how  long it gets. :) Sounds alright?

**Comment by nicholashagen** [comment]
I have the first draft ready.  Is it preferred to just post as a comment here, or is there a more preferred place?

**Comment by stefanjudis** [comment]
Personally, I prefer a shared google doc because it's perfect for collaboration but it's up to you at the end. :)

**Comment by nicholashagen** [comment]
https://docs.google.com/document/d/1BmAg_qgpugBT2PoZIneRO5vtZJM52MBnETzd6N7vYwc/edit?usp=sharing

**Comment by stefanjudis** [comment]
@nicholashagen can you give me comment access? :)

**Comment by nicholashagen** [comment]
Thanks @stefanjudis 

I updated the document to reflect your comments.  All made perfect sense.  I also updated the title, though still thinking it through, so I may change it if anything better comes to mind.  Give it another quick read-over and let me know what you need next.

Thanks again!

**Comment by stefanjudis** [comment]
Hey @nicholashagen,

alright. I'll hand this piece now to our editorial team and then we're good to go! 🎉

**Comment by bradsoo** [comment]
Hi @nicholashagen 
I'm Brad, Technical Writer for Contentful, and I'm your editor for this article. What you have so far looks good and I'm just going through with some edits, then we should be good to go!

**Comment by nicholashagen** [comment]
Thanks @bradsoo

The comments you made looked great. I went through, read and resolved each. I’ll continue to monitor and resolve as you read through. Thanks much!

**Comment by bradsoo** [comment]
@nicholashagen Thanks for that and keeping up with the editing/comments. Was attending a conference last week so I was reviewing your document sporadically over several days. 

Everything looks good to go on my side and I have a feature image ready for the blog post. I just need your sign off now and the article will be online as soon as tomorrow!

**Comment by nicholashagen** [comment]
Are there any further edits on this doc, or what are the next steps?  Thanks much!

**Comment by bradsoo** [comment]
Editing on my side is complete and the next step is for you to give the thumbs up on publishing. After the article is published, Stefan will reach out to you on the thank you package.

**Comment by nicholashagen** [comment]
Gave it one last look over, and I we are good to go.  +1 from me.

**Comment by bradsoo** [comment]
Hi @nicholashagen one last request, I will need a profile photo of you and a 1-2 line summary for your author profile that will appear at the end of the blog post (as seen in posts here http://contentful.com/blog). Could you please send this to me at brad.soo [at] contentful.com?

**Comment by bradsoo** [comment]
Hi @nicholashagen, your article is now online at: https://www.contentful.com/blog/2018/09/25/3-methods-resolve-graphql-endpoints.

Thanks for contributing. @stefanjudis will approach you with closing steps (i.e., thank you package).

**Comment by stefanjudis** [comment]
Hey @nicholashagen,

thanks so much for the article. It turned into a very nice piece! I'll reach out to you this week to get the package ready. :)

**Comment by nicholashagen** [comment]
Sounds great. It was great to have an easy straightforward process to submit through.
