### ISSUE TITLE
How to Build a Static Site E-Commerce with Jekyll, Contentful, and Commerce Layer

### ISSUE THREAD

**Issue by fconforti** [contentful/contribution-program#25]
Hello,

My name is Filippo, I'm the founder and CEO of [Commerce Layer](https://commercelayer.io/), and I believe that static sites are the future of e-commerce. I'd love to write a guest post on the Contentful blog. Please find the outline below.

Looking forward to your thoughts.

Thanks!
F.

## Intro

Static sites are the future: they are secure, fast and scalable. For e-commerce, being secure is a must have. Being fast and scalable means boosting conversions at a fraction of infratructure's cost. In this article, we will walk you through a step-by-step tutorial on how to build a static site e-commerce from scratch, on a [JAMstack](https://jamstack.org/) architecture.

### Tools

* [Jekyll](https://jekyllrb.com/) as the SSG
* [Contentful](https://www.contentful.com/) to manage content
* [Commerce Layer](https://commercelayer.io/) as the e-commerce platform
* [Github](https://github.com/) for code versioning 
* [Netlify](https://www.netlify.com/) for deployment and content delivery

By reading this blog post you will learn:

* What is the JAMstack and why it's so valuable
* How to use Jekyll to build static websites
* How to use Contentful as the CMS for static websites
* How to transform any static website into a full-featured e-commerce with Commerce Layer
* How to setup continuous integration with Github + Netlify

## Tutorial

- [ ] What is the JAMstack?
- [ ] Getting started with Jekyll
	- [ ] Setup your project
	- [ ] Create the brand page
	- [ ] Create the category page
	- [ ] Create the product page
	- [ ] Push to Github
- [ ] Manage the product catalogue on Contentful
	- [ ] Create a free developer account on Contentful
	- [ ] Create a new space using the "Product Catalogue" template
	- [ ] Install the Contentful plugin for Jekyll
	- [ ] Pull demo data from Contentful into Jekyll
- [ ] Make the product catalogue shoppable with Commerce Layer
	- [ ] Create a free developer account on Commerce Layer
	- [ ] Create a new organization with test data
	- [ ] Install the Commerce Layer CLI
	- [ ] Push test data into Contentful through the CLI
	- [ ] Pull test data from Contentful into Jekyll
	- [ ] Add a shopping cart to your static site
	- [ ] Add a checkout to your static site
- [ ] Deploy to Netlify
	- [ ] Create a free account on Netlify
	- [ ] Connect your Github repo
	- [ ] Go live!

## Summary

What we've done and learned. What's next.

**Comment by stefanjudis** [comment]
@fconforti 😲

This looks awesome! I would love to read that and see it in action. :)

As the process goes, I added this issue to the project board in the "draft in progress" stage. If you need any help with this let me know – happy to bounce ideas or give feedback. :)

Thanks! 🎉

**Comment by fconforti** [comment]
Thank you, @stefanjudis :)

I'll start working on the first draft and I'll keep you posted on my progress.
Stay tuned! :)

Cheers,
F.

**Comment by stefanjudis** [comment]
Awesome! 🎉

**Comment by fconforti** [comment]
Hey @stefanjudis 

I should be done with the coding part of the tutorial. It's a multi-country, multi-language e-commerce demo that leverages Contentful for content and Commerce Layer for commerce. You can see the result deployed to [Netlify](https://elegant-chandrasekhar-d86416.netlify.com/) and the source code on [Github](https://github.com/commercelayer/contentful-commerce). The readme contains the steps that should go in the article.

Looking forward to your feedback.

Thanks!
F.

**Comment by stefanjudis** [comment]
Hey Filippo,

this looks great with nice detail.

I wonder though, if the article should explain maybe more the core concepts and functionality and could point to the repository for people being interested in trying it out.

I could imagine many people need an introduction to "how to do a static ecommerce site" first. :)

What do you think about that?

**Comment by fconforti** [comment]
@stefanjudis 

Absolutely!

I just shared the coding part with you to get a first impression. The next step will be to write down the article, with a rich introduction about the benefits of building static ecommerce sites.

Question: which format do you prefer for the article? Should I share a markdown document? Or maybe a Google doc?

Thanks,
F.

**Comment by stefanjudis** [comment]
Awesome! 🎉

Personally, I prefer Google docs with markdown in it, because the collab mode is great, but at the end, it's up to you. :)

**Comment by fconforti** [comment]
@stefanjudis 

Quick question: how do you prefer screenshots to be inserted in the document? Should I just upload the images to Google docs?

Thanks,
F.

**Comment by fconforti** [comment]
@stefanjudis 

I shared the first draft of the article on Google Docs (using your gmail address).
Let me know if you got the invitation.

Thanks,
F.

**Comment by stefanjudis** [comment]
@fconforti Sorry for the slight delay, I was conferencing last week. I'll check the article today and will provide feedback. :)

**Comment by fconforti** [comment]
@stefanjudis sounds good! Let me know if you need any clarification ;)

Thanks,
F.

**Comment by stefanjudis** [comment]
@fconforti 

Oh wow - thanks so much for writing this in-depth tutorial.

So here's my feedback:

I feel like it's a bit too long and it's missing a strong selling point of static sites (jekyll and contentful) with client-side rendering (commerce layer) and how they play together showing their benefits. You mention it briefly in the introduction but I feel like the strong connection of static with client-side e-commerce may be the main storyline working best for the Contentful blog.

Doing "static e-commerce" is still a new topic for a lot of people and I think for us and for you this is where it could have the most value for the readers of contentful.com. I believe also that a high-level article could rank good for the term "static e-commerce".

My recommendation would be to go even more high-level and educate people about the benefits and general flows in this area (maybe we can include some diagrams).

I would keep this tutorial and make it the link target and clear CTA for the article on contentful.com (maybe include it in the example repo) so that people see and get enlightened about benefits and then jump right into some code.

Does this make sense? Please let me know what you think. :)

**Comment by fconforti** [comment]
@stefanjudis

Thank you for your feedback.

I see what you mean, I actually have quite the same feeling :)

So, if I'm getting it right we should:

1. Move the tutorial to contentful.com/developers/docs/tutorials/
2. Enrich the first part of the article, highlighting the benefits of static e-commerce and adding a high-level schema/description of our stack
3. Replacing the tutorial with a link to 1.

Do you think this can work? :)

Thanks,
F.

**Comment by stefanjudis** [comment]
> Move the tutorial to contentful.com/developers/docs/tutorials/

I would have to discuss this with our documentation team first. We could move it to the repo itself though initially? I saw there's some overlap to the readme anyways?

> Enrich the first part of the article, highlighting the benefits of static e-commerce and adding a high-level schema/description of our stack

Yeah! 👍🏻 I'm thinking of graphics and core concepts how the mix would work and why it's great.

> Replacing the tutorial with a link to 1.

Not sure I understand that. 

Thanks Filippo for being open for feedback and have a great day!

**Comment by fconforti** [comment]
@stefanjudis 

>> Move the tutorial to contentful.com/developers/docs/tutorials/

> I would have to discuss this with our documentation team first. We could move it to the repo itself though initially? I saw there's some overlap to the readme anyways?

I cannot hide that being one of your "official" tutorials would be super fantastic :) but in case it's not feasible for any reason I will adapt the repo readme.

>> Enrich the first part of the article, highlighting the benefits of static e-commerce and adding a high-level schema/description of our stack

> Yeah! 👍🏻 I'm thinking of graphics and core concepts how the mix would work and why it's great.

Great! Will your content team help with the graphics?

>> Replacing the tutorial with a link to 1.

> Not sure I understand that.

Sorry... I meant to say that we would remove the tutorial part from the article and replace it with a link.

> Thanks Filippo for being open for feedback and have a great day!

Thank you, Stefan!

As next step, I will rework the first part of the article. In the meantime, let me know what your documentation team say about the tutorial.

Cheers :)

**Comment by fconforti** [comment]
@stefanjudis 

I just updated the [repo](https://github.com/commercelayer/contentful-commerce) with the step-by-step tutorial and I'll be working on the article today. 

Please let me know if you have any guideline for drawing the diagrams that I should follow.

Thanks,
F.

**Comment by fconforti** [comment]
@stefanjudis 

Just checking if you had the chance to review the article.

Thanks,
F.

**Comment by stefanjudis** [comment]
Hey Filippo, I will have a look today. Sorry about the delay. Was vacationing the last week. :)

**Comment by stefanjudis** [comment]
Hey Filippo, I will have a look today. Sorry about the delay. Was vacationing the last week. :)

**Comment by stefanjudis** [comment]
@fconforti I made a few comments. We're slowly getting there! 👌🏻 🎉

**Comment by fconforti** [comment]
@stefanjudis 

> Sorry about the delay. Was vacationing the last week. :)

No problem! :) Sorry for the push. The point is that [we are sponsoring](https://jamstackconf.com/#sponsors) the JAMstack conference and it would be great to have the article published before the end of this week.

> I made a few comments. We're slowly getting there! 👌🏻 🎉

I'm reviewing your comments right now and I'll get back to you asap. Thanks!

F.

**Comment by bradsoo** [comment]
@fconforti Thanks again for your contribution. For your records, the article is online at: https://www.contentful.com/blog/2018/11/07/how-build-static-site-ecommerce-jekyll-contentful-commerce-layer/ and has also been crossposted to Medium https://medium.com/@contentful/how-to-build-an-ecommerce-static-site-with-jekyll-contentful-and-commerce-layer-99fbe4957296

@stefanjudis will approach you with closing steps (i.e., thank you package).

**Comment by stefanjudis** [comment]
Thanks @fconforti. :)
