### ISSUE TITLE
A loosely-coupled approach to creating MailChimp campaigns with Contentful webhooks

### ISSUE THREAD

**Issue by pommiegranit** [contentful/contribution-program#26]
## Article suggestion

How-to on integrating MailChimp and Contentful to enable webhook-triggered creation and sending of email campaigns.

## Summary

Email is just another publishing channel for your Contentful content. By using webhooks and a cloud function, we can automatically create, and send, MailChimp campaigns. 

No more cut-and-pasting, no more typos. Published Contentful content delivered automatically to your audience's inboxes.

In this article we'll look at how to create a loosely-coupled workflow that allows the email design to be completely managed in MailChimp. We'll go through the building of a Python-based cloud function, called by a Contentful webhook that:

1. Gets a specified template using the MailChimp API
2. Populates the default content from the webhook payload (including grabbing any related entries or assets)
3. Creates a MailChimp campaign
4. Populates the campaign content
5. Sends the campaign

We'll also briefly cover content design considerations.

**Comment by pommiegranit** [comment]
No worries @stefanjudis.

I'll start working on the draft.

**Comment by pommiegranit** [comment]
@stefanjudis,

I've finished the first draft. How do you want me to provide it to you?

It's currently [on Google Docs](https://docs.google.com/document/d/1kZLL7x4iP7IRNx-9HyqMIeRt4YHUh6FamGeYUP7-7Ho/edit?usp=sharing).

Chris

**Comment by stefanjudis** [comment]
@pommiegranit Sorry for the slight delay, I was on vacation. Can you give me comment or suggestion rights (stefan.judis[at]contentful.com)? Gdocs works quite nicely for collaboration in my opinion.

**Comment by pommiegranit** [comment]
Don't apologise for being on holiday! I've given you commenting access - you should have received notification from Google Docs.

**Comment by Shy** [comment]
Hey @pommiegranit,

I'm helping @stefanjudis with the article. You might have seen some of my comments in the google doc already. I'm pretty happy with the article. I'm going to be looping in our Editorial team (@bradsoo)  who'll come in for one last editing pass and the logistics of getting it published. 

I'm really excited to see the published version!

**Comment by bradsoo** [comment]
Hi @pommiegranit  
I'm Brad, Technical Writer for Contentful. I'll be your editor for this article - Shy has looped me in on the details and sent me a link to the draft on GDocs. I've already ordered a feature image for the article and will get back to you with my edits and comments. If everything goes well, we could have this online in the coming days!

Cheers,
Brad

**Comment by pommiegranit** [comment]
Brad,

No worries. Do you want me to give you editing access?

Regards,

Chris

**Comment by bradsoo** [comment]
Also, our blog posts typically feature some basic information about the author, and I was wondering if you could provide me with a profile photo and short (2-3 line) description of yourself. My email is brad.soo [at] contentful.com.

You may also include links to your GitHub, Twitter and Linkedin profiles, relevant website for your portfolio or organization, and location.

**Comment by bradsoo** [comment]
@pommiegranit Thanks for the edit access! I've reviewed your article - I'll echo Shy that your article was in pretty good shape to begin with - and completed editing. The feature image should be delivered early next week by our designer and, if you have no further changes by then, we should be able to get your piece published after that!

Quick reminder to send over the author profile you'd like to see on the article (as described in my comment above) when you find the time to =)

**Comment by bradsoo** [comment]
Hi @pommiegranit , your article is now online at: https://www.contentful.com/blog/2018/11/30/mailchimp-campaign-contentful-webhooks-loose-coupling/ and has also been crossposted to Medium: https://medium.com/@contentful/a-loosely-coupled-approach-to-creating-mailchimp-campaigns-with-contentful-webhooks-5c04afca9f32 

Thanks for contributing. @Shy will approach you with closing steps (i.e., thank you package).
