### ISSUE TITLE
Building a static site w/ contentful, netlify, styles components, and gatsby v2

### ISSUE THREAD

**Issue by sepowitz** [contentful/contribution-program#27]
Hey! I’ve been building some client projects with contentful, netlify, styled components and gatsby v2 and would love to write a step-by-step article about the process. 

Would this be of interest?

**Comment by stefanjudis** [comment]
Oh yeah! ❤️ We would love to publish material about this. :)

Can you provide us with an outline so that we can discuss further steps?

**Comment by sepowitz** [comment]
Absolutely. What is the best way to share an outline?

**Comment by stefanjudis** [comment]
Sharing an outline can be done here... :) For the actual draft then I prefer google docs (because of the great collab mode), but we can use whatever you prefer. :)

**Comment by sepowitz** [comment]
Awesome! I will share a brief outline ASAP

**Comment by sepowitz** [comment]
## OUTLINE
## Building a Simple Portfolio site with Contentful, Gatsby v2, Styled Components, and Netlify

### Part 1: Introduction

- Introduce each technology, what they are for, and why they are cool :)
  - Part of this includes touching on what Gatsby v2 introduces
- Preview the minimal portfolio design we are going to implement
  - It will include a homepage, work/index, work/show, and contact page

### Part 2: Setup

- Go through each step in setting up the project
  e.g. Gatsby new, Setup free Contentful account, install Styled Components and render a component, deploy it all to netlify

### Part 3: Build

- Setup Routesz
- Fetch page data from contentful
- Build out first few SC
- Introduce nested routes
#### * I will obviously leave out some of the detail, otherwise this artcile will be crazy long, but will link to the repo for reference

### Part 4: Deploy

- Show how to create production branch with netlify
- Setup webhooks with contentful

### Part 5: Outro

- Talk about why this is a good approach e.g. ease-of-use, free/inexpensive, super fast, modern, SEO friendly

Let me know if you have any questions/thoughts!

**Comment by sepowitz** [comment]
Hey @stefanjudis not sure if you saw the above ^ outline I shared. Would love some feedback when you get a chance. 

Thanks!

**Comment by stefanjudis** [comment]
@sepowitz Sorry for the delay, I was vacationing. the outline looks good imo. I'm a little worried about the length though (as you also phrased concerns :D ).

I think we could cut the setup parts and link to docs and resources?

But apart from that, I think this looks 👌🏻! 

We would have to check how long we get, but for now I think that's a nice outline and with a little bit of back and forth during the writing this will turn out nicely!

**Comment by Shy** [comment]
@sepowitz, I wanted to check in and see if you're still interested in writing this article? Would be great to read a draft if you've had a chance to work on this.

**Comment by Shy** [comment]
@sepowitz, I wanted to check in and see if you're still interested in writing this article? Would be great to read a draft if you've had a chance to work on this. Since it's been a little bit I'm closing this ticket to cleanup the project board. If your still up for it feel free to reopen the ticket.
