### ISSUE TITLE
From Static to Dynamic with Zeit 2.0

### ISSUE THREAD

**Issue by david-genger** [contentful/contribution-program#29]
I would love to write about how the new Zeit 2.0 can be used with Contentful. with the new update of Zeit the possibilities are endless. 
As a huge fan of Netlify with more than a handful of websites live on Netlify, I feel that now is the time to level up and start using Zeit as the potential is enormous.

**Comment by Shy** [comment]
@david-genger, this sounds like a pretty cool article. Let's make it happen. 

If you could provide us with an [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) before starting to write we'll be able to give feedback and share ideas! :)

**Comment by david-genger** [comment]
Question: are we looking for an article geared towards developers or for marketing and business guys?
@Shy

**Comment by Shy** [comment]
Developers! 

![](https://media.giphy.com/media/enTimXqzmVXR6/giphy.gif)

**Comment by david-genger** [comment]
I'll try to use some of this energy of Steve Ballmer ⚡😊🎉

**Comment by david-genger** [comment]
**Title (suggestions)**
•	Frictionless writing, coding, publishing
•	From deploying in minutes to deploying in seconds
•	Edit anywhere, publish anywhere
•	Your content is liberated your servers should too!

**Objective 👁**
 the benefits of Ziet 2.0

**Main take ways 🦄**
After reading the article, you will understand how the new architecture that Zeit brings along will improve your publishing pipeline in aspects like security, maintenance, reliability, time to ask for your next raise!
When your content and servers are liberated there is no limit to what we can achieve! 

**Technical background 👩‍💻**
While we will be showing examples of code, but we will try to stick to concepts, so a small amount of knowledge is needed indifference of programming language.

**Meat Of Article 🥩**
Static is limitless (fully dynamic) with Zeit 2.0 (intro)
Benefits
•	Massive Concurrency
•	Unified
•	Fully universal and global
•	Language agnostic
•	No hard fail, only parts will fail
•	Build on git push

**Languages and frameworks 👩‍💻**
•	NextJs
•	Mettlesmith
•	Snipcart - ecommerce

**How (concept/outline) ❓**
•	Create files with ending associated with that language you are writing
•	Create now.js files and define your servers
•	Connect Zeit with GitHub 
•	PUSH! 🎉
•	Dream about the 156 containers or VM's you just created
	
**How (Practical - with examples)**
•	Create files with ending associated with that language you are writing
•	Create now.js files and define your servers
•	Connect Zeit with GitHub 
•	PUSH! 🎉
•	Dream about the 156 containers or VM's you just created

**Content (guide me on how to include Contentful here 😉)**
	Headless CMS and the marketing director, a love story
	

**Summary**
	You will see how your life will improve...

**Comment by david-genger** [comment]
What should be my next step, I should start writing or wait for feedback on the outline?

**Comment by Shy** [comment]
Hey David, 

Sorry about my slow response time. I've been out because of Thanksgiving. 

I think this looks good to go so once @bradsoo (our of our copywriters) drops by to leave feedback I'll move this into the writing stage.

**Comment by bradsoo** [comment]
Hi @david-genger 
I'm Brad, Technical Writer for Contentful. I'll be your editor for this article - I think the article idea sounds like a good one (sounds like something people would be interested in reading) and your outline looks 👌🏻!

I'd like to know more about your plans for the Meat and the How's - if you have something substantial to talk about, maybe you could consider splitting it into a 2-part article (I would imagine 1. Overview, benefits, meat, and then 2. How with concepts and examples).

Other than that, please share a draft when you're ready (we use GDocs for collaboration) and we can get your writing piece into shape for publishing. And I can certainly help with sprinkling in the "Headless CMS and the marketing director love story" bit.

Cheers,
Brad

**Comment by david-genger** [comment]
I'm currently working on the actual content, I will try to get it done within the next week or so.

**Comment by bradsoo** [comment]
Great, thanks for the update!

**Comment by Shy** [comment]
Hey @david-genger, wanted to check in and see if you had any updates?
