### ISSUE TITLE
Create a simple content calendar for your Contentful content

### ISSUE THREAD

**Issue by pommiegranit** [contentful/contribution-program#31]
A content calendar allows you to see at a glance when your content is being published. It's an essential component of any content manager's toolbox.

In this article we'll step through how to create your own content calendar. We'll build a single-page app that leverages the Contentful Management API to create a calendar view of your content. We'll even add the ability to change when a piece of content is published by dragging it to a new day.

----------

App will look something like this: 

![screen shot 2018-12-12 at 4 19 48 pm](https://user-images.githubusercontent.com/6424582/49848610-fefe6800-fe29-11e8-9612-8a064cca24ad.png)

The article will work through:

1. Considerations for the calendar (eg need for additional 'publish date' field)
2. Setting up an application in Contentful (OAuth / login)
3. Using the Content Management API to access and update unpublished content
4. Building the interface

The app will use: 
* [riot.js](https://riot.js.org) to build the interface (I find it much easier to work with than React)
* the [Bulma CSS framework](https://bulma.io)
* the Content Management API javascript library

**Comment by Shy** [comment]
Hey Chris. I'm excited to get to work with you again! 

I think this sounds awesome. I'm going to move it straight into the writing phase.

**Comment by pommiegranit** [comment]
I've given you both access to the Google doc. 

It's a pretty rough initial draft but I wanted to get it to you before the holidays!

**Comment by Shy** [comment]
Hey @pommiegranit, hope you had a good holiday and new year. @bradsoo and I both just got back from our holiday vacations and we'll hopefully be able to get you some feedback soon.

**Comment by bradsoo** [comment]
Hi @pommiegranit thanks for sharing the doc, I look forward to working with you again and I will go over that this week. I've scheduled time to work with you on this blog post, let's get it out this month =)

**Comment by Shy** [comment]
Article was posted so I'm closing this issue: https://www.contentful.com/blog/2019/01/24/create-content-calendar-contentful/

Thanks again @pommiegranit, hopefully, we can keep working together!
