### ISSUE TITLE
Using nginx with a simple config to reduce latency

### ISSUE THREAD

**Issue by peter-leonov** [contentful/contribution-program#32]
Hi guys,

Thanks for the great product!

In my team we use nginx to cache locally the content we get from `api.contentful.com`. The config is just a transparent caching proxy with all the goodness of nginx's `proxy_cache` directive, including background validation and stale version serving.

Do you think it's valuable to write an article like this for Contentful blog?

**Comment by Shy** [comment]
Hey @peter-leonov, sorry for the slow response. I must have missed this in all the scuffle once I got back from the holiday break. If you're still interested, I think it would be great to have you write up this article. 

The one concern I have is that we might confuse folks about how the built-in caching that Contentful has works, but I think we can work through that concern. 

If you could provide us with an [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) before starting to write we'll be able to give feedback and share ideas! :)

**Comment by Shy** [comment]
@peter-leonov, wanted to check in and see if your still interested. I'm closing the ticket since I haven't heard from you, but feel free to reopen it if your planning on writing this article.
