### ISSUE TITLE
Build a blog with Vuejs and Contentful

### ISSUE THREAD

**Issue by krissnawat** [contentful/contribution-program#33]
Want to contribute some  practical tutorials 

Thank

**Comment by Shy** [comment]
@krissnawat, That sounds awesome. Would you be able to spin up an outline of an article if you're still interested?

**Comment by krissnawat** [comment]
@Shy just publish demo for article on this
https://github.com/krissnawat/nuxtnuxt

**Comment by Shy** [comment]
Looks great. Let me know if you need any help on the [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md).

**Comment by krissnawat** [comment]
1.	NUXT JS : A SERVER SIDE RENDERING MODULE OVER VUE JS
2.	CONTENTFUL: A CONTENT MANAGEMENT TOOL
4.	BLOGGING USING NUXT AS SSR AND CONTENTFUL AS CLOUD API PLATFORM
5.	HOW TO CREATE SEO BLOG CONTENT USING NUXT AND CONTENTFUL

**Comment by Shy** [comment]
@krissnawat, I'm looking for something with more detail. Take a look at some of our closed issues for examples. https://github.com/contentful/contribution-program/issues/29#issuecomment-440454704 

https://github.com/contentful/contribution-program/issues/4#issuecomment-447198901

**Comment by krissnawat** [comment]
### Topic :
 - How to create blog using NuxtJS and Contentful  
 - Creating SEO blogs
   with NuxtJS and Contentful platform

### Objective

 - To understand benefits of NuxtJS and ContentFul for blog creation
 - To Set up Contentful
 - To connecting Contentful cloud platform to NuxtJS
 -  Using NuxtJS and Contentful for creating a blog

### Main Takeaways
- About NUXTJS (SSR over VueJS) and Contentful
- Learn how to set up and connect NuxtJS and Contentful
- Creating SEO blogs

### Technical Background
- Why Nuxt and Contentful

- Nuxtj.s is a higher level framework built over Vue.js framework for building server-side rendered Vue.js applications.

- Contentful provides infrastructures to write contents. Contents can be created, organized and allocated to any platform.

### Meat of Article

NuxtJS makes the SSR easier due its inbuild modules and helps to create SEO contents. The routes are automatically handled.

Contentful enables users to integrate the contentful with any framework in multi-channel network. It allows content team to create quick, intuitive, simple contents and increase the efficiency of production.

### Frameworks and platforms

 - NUXTJS

 - Contentful cloud platform

### How (Concept/Outline) on setting up NuxtJS?

 - Creating nuxt project

 - Installing nuxt modules

-  Setting up project in github

### How (Steps of setting up nuxt with contentful with screenshots)?

- Installing contentful module in nuxt

 - Coding with nuxt and contentful

### How (setting up contentful)?

- Signing into Contentful

- Creating your Contentful space

-  Authenticating Your Web Project

- Making your first Delivery API Call

### Summary
you learn how to use Nuxtjs and Contentful create some static blog

**Comment by Shy** [comment]
@krissnawat I'm going to move the ticket into the draft phase. Go ahead and get started turning this outline into a first draft. One of our Technical Copywriters should drop by to give you feedback as you're working.

**Comment by krissnawat** [comment]
### **Objective**

-   **To Set up Contentful :** This article aims to help bloggers setup contentful platform from creation of contenful account to deploying contentful delivery API to Nuxt Framework.
-   **To connect Contentful cloud platform to Nuxt.js :** After setup of contentful is complete, connect contentful platform to Nuxt framework using vue-cli.
-   **Using NuxtJS and Contentful for creating a blog:** Nuxt.js and Contentful is bound to create a much easier and stable blog. The provision of various predefined content structures of Contentful along with the preset arrangements of Nuxt.js simplifies the Vue application. It allows the developers and editors to work side by side on their blog. Thus, created blog loads faster as static and dynamically using Contenful APIs.

### **Main Takeaways**

#### **i. About NuxtJS (SSR over VueJS) and Contentful**

Through this article, users or bloggers can take away benefits of using Nuxt.js framework and contentful to create quick, sophisticated and efficient blogs. Nuxt.js framework developed over VueJS platform provides Server Side Rendering (SSR) facility which provides bloggers SEO contents. The idea behind using contentful as content management tool providing necessary steps to integrate both nuxt and contentful.

#### **ii. Learn how to set up and connect Nuxt.js and Contentful**

Before creating blogs using Nuxt and Contentful, it is very important to set up these platforms for a programmer/blogger. This article will provide point wise interpretation of how to setup both Nuxt.js project and Contentful tool as well as provide necessary steps in fetching contentful data to Nuxt project.

#### **iii. Creating SEO blogs**

Since use of Nuxt.js provides the facility of SSR which helps search engines to search through contents more easily and efficiently. One of the main takeaways can be to learn create SEO content blogs using Nuxt platform and contentful.

### **Technical Background**

#### **i. Why Nuxt and Contentful**

Nuxt.js is a higher level framework built over Vue.js framework for building server-side rendered Vue.js applications. It automatically generates Vue router configuration to shorten the lengthy router config file in Vue application. It allows us to add configurations in Config file as required to resolve the standardized way of configuration in Vue.js.

Vue applications are slow to load. Its framework behavior are difficult to change. the framework Nuxt.js is created in order to overcome all these complexities in Vue.js applications. It offers various out of the box features and a decent performance level.

Contentful is a content infrastructure platform where blogs can be generated, organized and allocated to any platform. Besides this, it offers freedom to create your own model. Final products are delivered much faster as developers and editors work simultaneously.

The use of powerful APIs along with topnotch documentation and samples to helps build prototypes faster and easier. It was created to help professional developers create programmable contents, overcoming drawbacks of CMSs that are designed to manage page-centric websites.

#### **ii.** **SEO Blogs**

Blog is a website where information on various topics are posted in a sequential order where the recent upload appears at the top. The increasing use of blogs nowadays has encouraged the authors to hire professional editors to edit the posts in more presentable and comprehensible way.

These blogs are optimized to keywords that are then detected by SEO to display them in search results. Search Engine Optimization, briefly known as SEO, gathers information about every pages in the web to provide exactly the page the user is looking for. A special algorithm is used to scan every word, title, link, words used in links as well as the reputation of the website to deduce the search results required by the user. The blogs that fit the algorithm best are ranked higher in search results. The algorithm is frequently modified focusing on entities like localization, page authority and click through rate as well as search through voice assistants.

### **Meat of Article**

Framework Nuxt.js makes the Server Side Rendering easier due its inbuild modules and helps to create SEO contents. The routes are automatically handled. Contentful enables users to integrate the contentful with any framework in multi-channel network. It allows content team to create quick, intuitive, simple contents and increase the efficiency of production. Integration of these to advance tool and framework will allow bloggers to create search engine efficient blogs which will appear as initial links in search engines. The setup of nuxt project and contentful is initial process where as fetching the contentful data through contentful API to Nuxt template will be the end process.

### **Frameworks and platforms**

1.  Nuxt.JS JavaScript framework
2.  Contentful cloud platform

### **How to set up Nuxt.js using Vue-CLI?** **(Concept/Outline)**

Nuxt.js is a simple yet powerful framework built on top of VueJS framework for easier and simpler usage of Vue.js application. Hence, Vue CLI is required to begin with Nuxt.js. Its architecture and commands are similar to Vue CLI.

To install Vue CLI you will require Node Package Manager (NPM) which can be easily downloaded from nodejs official site.

Using NPM, use the following command to install it:

      $ npm install -g vue-cli

After the cli is installed, use the following commands to initialize the application with Nuxt starter template:

      $ vue init nuxt-community/starter-template <project-name>

      $ cd <project-name>

      $ npm install

Launch your project

      $ npm run dev

Now, Nuxt logo will appear in your browser along with the title of your project and description you entered in the CLI setup.

### **How to set up contentful using contentful-CLI?**

Before integrating contentful API to different platforms you will need to set up a space, create a content model and fill it with some data.

While you setup the contentful space manually you can also do it using contentful-CLI and create content space and fill it with data.

The contentful-CLI can be installed using NPM, using command:

            $ npm i -g contentful-cli

With CLI available to you, now you have to authorize it through contentful login. This command will open a new browser window through which you can create a new account or login then retrieve a new access token.

            $ contentful login

Now you can create contentful space using command :

           $ contentful space create --name 'Nuxt with Contentful tutorial'

Now created space is filled with contents. The CLI tool will show you the space ID which you will need in a second.

To transfer content between spaces you can use the contentful space export and contentful space import commands from the Contentful CLI.

Then, use seed with a defined –space-id flag.

               $ contentful space use

              ? Please select a space:

               ...

              ❯ Nuxt with Contentful tutorial(k8ig0fsx7n)

               ...

Now you can import some data to contentful

              # after space selection using `contentful space use`

              $ contentful space seed --template blog

              # without space selection

             $ contentful space seed --template blog --space-id <your-new-space-id>

New space has now a set up content model including a person and a blog post content types.

Last step do is to create a Content Delivery API access token. You can do this using the web app or also via the CLI.

                 $ contentful space accesstoken create --name Nuxt with Contentful Tutorial

                 Successfully created access token nuxt (1234567890xxxxxxxxxxx)

### **How to set up Nuxt.js with Contentful?**

The project above has only the root index available defined as ./pages/index.vue. To make it use Contentful we have to do two things:

1.  Register the Contentful JavaScript CDA SDK
2.  Fetch data in the index.vue page component

#### **Step 1: Register the Contentful JavaScript CDA SDK**

Using Contentful SDK, Contentful is easily integrated as a module in Nuxt project . The command for it is:

$ npm install --save contentful

Nuxt.js provides plugins directory to make custom code available on the server (the static pre-rendering) and client side (the dynamic re-rendering). Here, the JavaScript SDK is based on axios which makes it possible to use it in the Node.js and browser context.

To use it, create a new file in the plugins directory called contentful.js.

> // ./plugins/contentful.js

 const contentful = require('contentful')

// use default environment config for convenience

// these will be set via `env` property in nuxt.config.js

const config = {

  space: process.env.CTF_SPACE_ID,

  accessToken: process.env.CTF_CDA_ACCESS_TOKEN

}

// export `createClient` to use it in page components

module.exports = {

  createClient () {

    return contentful.createClient(config)

  }

}

Now you have to define the used environment variables. To avoid the need for setting all the environment variables in the CLI when running e.g. npm run dev you can set up a new config file called .contentful.json. This file includes the needed configuration:

-   entry ID of the person (the owner of the blog)
-   content type ID of blog posts to fetch the posts data
-   your space ID
-   content delivery access token

In the nuxt.config.js you can then require the config file and make it available in the plugins file through the env property.

> // ./nuxt.config.js

const config = require('./.contentful.json')

module.exports = {

  // ...

  env: {

    CTF_SPACE_ID: config.CTF_SPACE_ID,

    CTF_CDA_ACCESS_TOKEN: config.CTF_CDA_ACCESS_TOKEN,

    CTF_PERSON_ID: config.CTF_PERSON_ID,

    CTF_BLOG_POST_TYPE_ID: config.CTF_BLOG_POST_TYPE_ID

  }

  // ...

}

#### **Step 2: Fetch data in the index.vue page component**

Nuxt.js defines conventions which defines what pages and routes should be available. The example template created already the file ./pages/index.vue for you.

In Nuxt.js you can define asynchronous data for every page component. There is fetching of data during build time and later before every page navigation.

//index.vue

<template>

   <section class="section">

      <div class="container">

         <div class="columns">

            <div class="column is-offset-2 is-8">

               <h1 class="title is-2">Latest Posts</h1>

               <hr>

               <h2 class="title is-4" v-for="(post, index) in posts" :key="index">

                  <nuxt-link :to="{name : 'blogpost',params: { post : post.fields.slug}}">{{ post.fields.title }}</nuxt-link>

               </h2>

            </div>

         </div>

      </div>

   </section>

</template>

<script>

  import {createClient} from '~/plugins/contentful.js'

  const client = createClient()

  export default {

    // `env` is available in the context object

    asyncData ({env}) {

      return Promise.all([

        // fetch the owner of the blog

        client.getEntries({

          'sys.id': env.CTF_PERSON_ID

        }),

        // fetch all blog posts sorted by creation date

        client.getEntries({

          'content_type': env.CTF_BLOG_POST_TYPE_ID,

          order: '-sys.createdAt'

        })

      ]).then(([entries, posts]) => {

        // return data that should be available

        // in the template

        return {

          posts: posts.items

        }

      }).catch(console.error)

    }

  }

</script>

//blog.vue

<template>

  <section class="section">

    <div class="container">

      <div class="columns">

        <div class="column is-offset-2 is-8">

          <p class="subtitle is-6">

            <nuxt-link :to="{name :'blog'}">Back to Blog home</nuxt-link>

          </p>

          <h1 class="title is-2">

            {{ $route.params.post.title }}

          </h1>

          <hr>

          <div class="content">{{$route.params.post.content}}</div>

        </div>

      </div>

    </div>

  </section>

</template>

These few lines will import the Contentful plugin you just wrote and create a new SDK client. You see that Nuxt.js also provides shorthands for the plugins directory which makes it really easy to import our Contentful plugin (~/plugins/contentful.js).

For production, you can run npm run generate to statically generate the pages.

The results of the page are:

Index.vue

![](https://www.reactninja.io/wp-content/uploads/2019/03/Capture.png)

When you click on title of the posts, it routes to following pages :

Blog.vue pages

![](https://www.reactninja.io/wp-content/uploads/2019/03/Capture-1.png)

![](https://www.reactninja.io/wp-content/uploads/2019/03/Capture-2.png)

**Summary**

This was a quick walkthrough what you can achieve in five minutes using our article.

Using Nuxt.js and Contentful you can create a universal JavaScript application rather quickly without much operationals overhead. You can simply build the stack and then push it to your CDN of choice. The above steps will help to create easy, efficient and SEO friendly blogs.

Hope this article helped you!! ENJOY!!!

**Comment by bradsoo** [comment]
Hi @krissnawat I'm Brad, Technical Writer at Contentful. I'll be working with you on getting the piece into publish-ready state. The material you've written so far looks amazing. I'll get this into a Google Doc and make my edits there (for change tracking and collaboration). What is your email address so I may share the doc with you?

**Comment by krissnawat** [comment]
@bradsoo krissanawat101[at]gmail

**Comment by krissnawat** [comment]
@bradsoo what going on?

**Comment by bradsoo** [comment]
Hi @krissnawat sorry for the delay in getting back to you. I have a list of priority blog posts I'm working on, but I do have yours in the queue. I will start work on yours as soon as I am able.

**Comment by krissnawat** [comment]
what the waste my time

**Comment by realityking** [comment]
Hey @krissnawat,

My name is Rouven, I lead the DevRel team here at Contentful. Please accept my apologies for leaving you hanging here. Unfortunately Brad has left company and this blog post wasn't accounted for in the handover. This should never have happened.

Another editor, Maria, will take this over and we'll have it in Google Docs by the end of this week. You can reach her at maria.valatkaite[at]contentful[dot]com and myself at rouven[at]contentful[dot]com

Thank you,
Rouven

**Comment by Shy** [comment]
Closing since the article was published.
