### ISSUE TITLE
React native + GraphQL + Contentful 

### ISSUE THREAD

**Issue by krissnawat** [contentful/contribution-program#34]
Hi @Shy 
I plan to create react native app and using GraphQL / Contentful and share story again 
Here some app screenshots 
![](http://i.imgur.com/Tvbg3oO.jpg)

**Comment by Shy** [comment]
Closing this since Kris and I chatted about this via email.

**Comment by Shy** [comment]
Reopening since it's been a month since @krissnawat's last post. @krissnawat would you be able to provide us an outline for our review?

**Comment by krissnawat** [comment]
### Topic 💯 
Bring your blog to mobile with React native and Contentful
Creating React native blog and Contentful
Gain your ads revenue with React Native and ContentFul
Delivery your blog post on Mobile with React Native and ContentFul
### Objective
To understand benefits of React Native and ContentFul for blog monetization
To Set up Contentful along with React Native
Delivery content on new experience device
Using React Native and Contentful for content delivery
###  Main Takeaways
About Mobile Device and Contentful
Learn how to set up and connect React Native and Contentful
Serving content on mobile
###  Technical Background
Why React Native and Contentful

React Native is a mobile development framework building on top React.js framework for building  Native mobile.

Contentful provides infrastructures to write contents. Contents can be created, organized and allocated to any platform.

###  Meat of Article
React Native makes the mobile development fun and easier due it provides a component and helps to build Android and iOS app without headache.

Contentful enables users to integrate the contentful with any framework in a multi-channel network. It allows the content team to create quick, intuitive, simple contents and increase the efficiency of production.

### Frameworks and platforms
- React Native
- Contentful cloud platform

### How (Concept/Outline) on setting up React Native?

 - Creating react native project with react native CLI React Native for
    Designers
  - Styled Components in React Native
    
  -  Props and Icons
    
-    Static Data and Loop
    
-    States and Animations
    
-    basic Redux for React Native
    
-    Fetch API Data
    
-    Screens and Navigation
    
-    Passing Data in React Native
    
-    GraphQL and Contentful
    
-    HTML and Markdown on React native

 - Adapting for iPad and Android

### Summary
you learn how to use React Native and Contentful create some static blog

**Comment by Ameliawb** [comment]
Hi @krissnawat, good to meet you I am the new Dev Evangelist (SF) for Contentful and I'd be happy to give you some feedback on your story.  I think you have a really strong outline, I look forward to reading the finished piece.  I have a few notes that could help me understand where you are coming from:

**Comment by Ameliawb** [comment]
Hi @krissnawat, good to meet you I'm a new Dev Evangelist for Contentful and I'd be happy to give you some feedback on your story. I think you have a really strong outline. I have a few notes that could help me understand where you are coming from: 

In your bullet point: 

“React Native makes the mobile development fun and easier due it provides a component and helps to build Android and iOS app without headache.” 

It would be cool to have an example from your own personal experience as to why React Native makes mobile development fun and easier.  Secondly what sort of headaches are you hoping people can avoid? Even if you just give me a list of key words it can help us link to a few other stories or help connect to our community, this way they may see a bit of their own story in yours.

An example of what I’m talking about here in [this article:](https://blog.usejournal.com/5-super-reasons-to-love-react-js-b57505535ea5
)

She has s good story structure, she mentioned that her company was redesigning their GUI, this gives us a solid example of where she was, **(at her company)** and why her team used it **(designing a GUI)** and why she was excited **(virtual Dom)**.   I look forward to reading the finished piece! Have a great week 🎉

**Comment by Shy** [comment]
Closing this since it's been a while since it had an movement.
