### ISSUE TITLE
Building a better podcast with Contentful and Sinatra

### ISSUE THREAD

**Issue by teemutammela** [contentful/contribution-program#35]
Hi there,

Last year I attended [Contentful Developers Meetup Helsinki #2](https://www.meetup.com/Contentful-Developers-Meetup-Helsinki/events/255360681/) as a guest speaker and gave a presentation about my podcast website AuralCandy.Net and the technology stack it is built upon (Contentful, Ruby, Sinatra and Heroku).

I adopted my presentation into a blog/article form ([read here](https://www.evernote.com/l/AQ0zpVTgAIlGFregP-zVXLEjxxD8gDHpzPA)) and released the [source code](https://github.com/teemutammela/auralcandy.net) for anyone wishing to learn more about developing Contentful applications using Ruby and Sinatra.

**Comment by Shy** [comment]
Hey @teemutammela, we'd be happy to post your article. Would you be able to move it into a google doc and share it with Jo (jo.fraser @ contentful.com), one of our editors, who would be able to provide feedback and help polish the article up.

**Comment by teemutammela** [comment]
@Shy Thanks, I'll convert the article to Google Docs format and send the link to Jo Fraser.

**Comment by Shy** [comment]
Thanks @teemutammela for publishing your article with us. 

It's live on the Contentful website at https://www.contentful.com/blog/2019/05/22/building-a-better-podcast-with-contentful-and-sinatra/

![](https://i.giphy.com/4xpB3eE00FfBm.gif)
