### ISSUE TITLE
Article suggestion: Build a website using Gatsby.js and Contentful 

### ISSUE THREAD

**Issue by senta-nakazato** [contentful/contribution-program#36]
Hello there,

I built website called [Contentful Explore](https://contentful-explore.netlify.com/) to know more how to use Contentful.  

I am interested in writing a blog post about how I made this website using Contentful with Gatsby.js.

Can you please let me know what do you think about it?

Thanks,

**Comment by Shy** [comment]
Hey @senta-nakazato,

Sorry for my slow response on this. I must have missed the notification. We'd love to have an article on Contentful Explore.

If you could provide us with an [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) before starting to write we'll be able to give feedback and share ideas! :)

**Comment by senta-nakazato** [comment]
@Shy 
Sorry that I didn't mention you, and thanks for your response.

Actually I am not good at writing English so I wanna make this blog simple.

I have two ideas about blog
1. Write about how to make this site with Gatsby.js and Contentful, writing set up step by step.
like this [article](https://www.contentful.com/blog/2019/06/14/build-website-nuxt-contentful/)

2. How to set up and render Rich Text and MDX

Do you have some advices? Thanks!

**Comment by Shy** [comment]
I think an article on Rich Text and MDX could be really interesting. We've had a lot of articles about Gatsby already so an article on Rich Text would be different! 

Would you be able to [export your content model](https://github.com/contentful/contentful-export) for the project and commit it to the repo? 

You can see my [project on super sentai to see how I explain importing content](https://github.com/contentful-labs/zappa-contentful#set-up-the-content-model-and-update-the-api-keys). You're welcome to reuse that text.

**Comment by Shy** [comment]
@senta-nakazato, just wanted to check in and see if you had a chance to create an outline on the RT and MDX article?

**Comment by senta-nakazato** [comment]
@Shy 
sorry for late to tell you this, but I started new job and it is difficult to have time to write this.
I should put off...... I really wanna try to contribute in future.
Thanks for your kindness!

**Comment by Shy** [comment]
Congratulations! That's very exciting. Feel free to reopen this issue anytime.
