### ISSUE TITLE
Author Wanted: Static Sites, can you do E-Commerce? 

### ISSUE THREAD

**Issue by Shy** [contentful/contribution-program#38]

**Comment by azer53** [comment]
Wanting to write about this for a whole time, if the request is still needed, happy to help!

**Comment by Shy** [comment]
Yep. We're still looking for this. Would you be able to create a small [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) so we can give you feedback before you start writing?

**Comment by Shy** [comment]
@azer53 just wanted to check in and see if you still wanted to work on this post? Happy to give you feedback if you've got any question or concerns.

**Comment by arhoy** [comment]
Hello! I am interested in writing an article for you guys using Gatsby + Contentful + Snipcart for ecommerce. Are you guys still open ?!

**Comment by Shy** [comment]
Hey @arhoy, yep we're still open. I'll reassign the ticket to you.

Would you be able to create a small [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) so we can give you feedback before you start writing?

**Comment by arhoy** [comment]
Okay I can create an outline. Where should I send the outline to?

**Comment by Shy** [comment]
You can just post it here.

**Comment by arhoy** [comment]
### Title: Building an ecommerce site with Gatsby, Contentful and Snipcart

Technical Background: 
Some familiarity with React, Gastby or JavaScript. 

Intro:
Coming from a React background with some experience in Gatsby a static site generator, I wanted to use the JAM stack to create a blazingly fast, free yet powerful ecommerce solution that could work for both small or med size companies and could scale easily. This article shows you how you can get started


Takeaways: 

Why I chose Snipcart + Gatsby + Contentful together.
Setting up a ecommerce site using these powerful tools


Outline: 

Brief Gatsby set up ( assuming readers are already familiar )
Using Contentful	
Creating the product content model ( inside contentful )
Create some sample content (inside contentful)
Connecting Contentful and Gatsby
Rending all products
Creating seperate product pages

SnipCart 
Intro to snipcart, sign up and pricing model
Connecting Snipcart with our current Contentful inventory
Adding checkout cart
Testing
Netlify
Deploying site to Netlify
Adding in Contentful Hook to rebuild site on change


This example will be based on my current live demo found [here](https://fashiontwo.netlify.com/#/)

**Comment by Shy** [comment]
Would it be possible for you to mention the snipcart extension we have in our marketplace? 

Otherwise I'm cool with this outline. I'm gonna move it into the writing stage.

**Comment by arhoy** [comment]
Okay great! I will write in the next couple days! Should I post it here too once the draft is completed?

**Comment by Shy** [comment]
Yep. If you could leave us a google doc Liz and I can start commenting with feedback.

**Comment by Shy** [comment]
Logging that @arhoy sent me an email with a draft to review. Tagging @Liz0 on the ticket since we're on the editing phase.
