### ISSUE TITLE
Rest to GraphQL - how to proxy a REST API into a GraphQL API

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contribution-program#4]

**Comment by ksurendra** [comment]
Can you add some more details on this?

**Comment by stefanjudis** [comment]
I'd love to learn how you could set up your own GraphQL server even when the services you rely on are not supporting Graphql and only provide REST APIs. :) I know some people do exactly that and I'd love to read how much effort it is. :)

**Comment by jsjoeio** [comment]
Thanks @Shy ! I will get started on an outline and share it here soon :)

**Comment by jsjoeio** [comment]
Hey, just wanted to check in and let you know I'm still working on the outline :)

**Comment by jsjoeio** [comment]
@Shy Here's my first shot at the outline (feedback warmly welcomed):
  
### Introduction
> "You are in a front-end developer team that wants to try GraphQL without asking for the backend team to implement a GraphQL server." --[Apollo Docs](https://www.apollographql.com/docs/link/links/rest.html)

- Discuss how GraphQL is hot, very popular (reference state of JavaScript) and how many people want to "test it out" before fully diving in. 

### Main Takeaways
- Goal of this post is to show you how to proxy a REST API into a GraphQL API using [`apollo-link-rest`](https://github.com/apollographql/apollo-link-rest)
- by the end of it, you will know how to use exisiting REST endpoints with GraphQL on the front end
- you'll also understand the pros & cons of using GraphQL on the front end

### Technical Background
- list of prerequisites (with brief descriptions)
  - solid understanding of JavaScript
  - know how to work with a REST API
  - understand basic core concepts of GraphQL
- discuss benefits of GraphQL (with sources to back up information)

### Explain how it's done
- [ ] Clone basic repo (it'll be a React app, very simple that has CRUD operations with a simple API)
- [ ] Refactor each operation (C, R, U, & D) to use `apollo-rest-link` and queries and mutations

### Summary
- reiterate the excitement around GraphQL
- summarize what we did in steps (show the process)
- remind them that they can try out GraphQL sooner than later :D

**Comment by Shy** [comment]
@jsjoeio. I like this outline. I'll go ahead and push it into the writing phase.

**Comment by bradsoo** [comment]
Hi @jsjoeio , I'm Brad, Technical Writer at Contentful. I'll be working with you on getting the piece into publish-ready state. Just wanted to check in on your progress and if you needed any assistance.

**Comment by jsjoeio** [comment]
Hey @bradsoo ! Nice to meet you. Thanks for checking-in. This month was pretty busy (workshops, anniversary, birthday, moving houses, etc) so the blog post has fallen to the way side 😅 but I will aim to get you something to critique by February 1st. Is that alright?

**Comment by bradsoo** [comment]
Works great for me, @jsjoeio. Feel free to email or share a collaborative document with me at brad.soo at contentful.com

**Comment by jsjoeio** [comment]
Sounds good. Thanks @bradsoo ! Will do.

**Comment by jsjoeio** [comment]
Hey Brad. I started a [Google Doc](https://docs.google.com/document/d/13cQLcYmkb1uXSDqDgzgzhefwJtLQ658SQz6zpr1NPo0/) and shared wit with you.

**Comment by bradsoo** [comment]
@jsjoeio I was out of office for a little over a week, and just resumed on Monday, Just a tiny heads up to let you know I have been and will be working on your post in the next few days so we can get it published.

**Comment by jsjoeio** [comment]
@bradsoo That's okay. Thanks for the update. 

It's only 50% complete so that's okay. I will be working on it this week/next week so hopefully I can get it 100% complete soon.

**Comment by bradsoo** [comment]
Great, thanks. Please let me know when you think you've hit that 100% - the sooner you can finish contributing on your end, the sooner I can work on it and complete it on mine!

**Comment by jsjoeio** [comment]
@bradsoo I think I've hit that 100%

Please take a look at your earliest conveniences: [Link to Google Doc](https://docs.google.com/document/d/13cQLcYmkb1uXSDqDgzgzhefwJtLQ658SQz6zpr1NPo0/edit#)

Definitely a little bit of touching up to do but all the content is there. I'm going to also see if a friend from Apollo can take a look to make sure the technical part looks good too.

**Comment by bradsoo** [comment]
@jsjoeio I've completed the edits and contributions from my side and it looks good to me. If you're good with the state of the article, I can move it to the next stage to prepare for publishing.

Also, I'd also need an author bio from you. If you could provide me with a short 2-3 line profile and photo that would be great. You can send them to brad.soo [at] contentful

Optionally you can include include GitHub, Twitter and Linkedin profiles, relevant website for your portfolio or organization, and location.

**Comment by jsjoeio** [comment]
@bradsoo Awesome! Thanks for the edits. Just gave it once last read and made a few minor tweaks. I also made sure the Codesandboxes were looking good. I think we're ready to move onto the next stage.

I will email you a bio right now.

**Comment by Shy** [comment]
Closing this since we published the article. For anyone finding this issue check it out at: https://www.contentful.com/blog/2019/03/13/implementing-graphql-rest-api/
