### ISSUE TITLE
Author Wanted: How to talk to a Content Creator

### ISSUE THREAD

**Issue by Shy** [contentful/contribution-program#46]

**Comment by chantelle-s** [comment]
Hi Shy! Currently, I am a content manager/strategist at TELUS and an avid Contentful user. I would be happy to use my experience to write about this topic.

Is this still a topic your team wanted to explore?

**Comment by Shy** [comment]
Hey @chantelle-s, sorry about my slow response. I just got back from sabbatical and I'm still getting caught up with all things Contentful.

We're still looking for an author on this one. Would you be able to shoot me an email (shy@contentful.com) and I'll make an introduction to our MarCom team who can help get the ball rolling on our side.

**Comment by chantelle-s** [comment]
No problem at all! I just sent an email - I look forward to hearing from you
