### ISSUE TITLE
Article: Migrating WordPress to CF

### ISSUE THREAD

**Issue by malorie16** [contentful/contribution-program#49]
Hi there!

Liz Osterloh and I talked about my blog post on twitter and asked me to make a GH issue for my post so that the devrel team can take it from here and do a technical check!

Here's a link to a [google doc](https://docs.google.com/document/d/1DpJOdajpPX33j6UNbEOC_MXdxdht_nF3OFrUZdxiXrc/edit?usp=sharing) of the post.

Feel free to reach out with questions or if you need additional information!

**Comment by Liz0** [comment]
Thanks Malorie!

**Comment by Shy** [comment]
Hey Malorie,

Just wanted to get back to you about this blog post. You're posts about migrations actually caused us to have a chat internally about our best practices for migrations and we've decided that we want to produce some of our own content around this topic that we'll be putting in the docs. We're not going to be able to moving forward with your blog post at this moment. 

That said I know you've done a bunch of work and I'd love to send you a swag package as a thank you. If you shoot me an email (shy@contentful.com) with your mailing address I'll get that sent over ASAP. 

If you've got any other projects with Contentful let me know and we'd love to feature them in the Contribution program in the future.

Shy
