### ISSUE TITLE
Choosing the right static site generator for your project's docs

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contribution-program#5]

**Comment by carolstran** [comment]
Not sure if this issue is up for grabs or not, but sent you a message on Twitter about it!

**Comment by stefanjudis** [comment]
We'd love to see a comparison about that... If you'd be up for doing it – I'm happy to move you to the editorial pipeline. :)

**Comment by carolstran** [comment]
Sure, sign me up 🎉

**Comment by stefanjudis** [comment]
[Done](https://github.com/contentful/contribution-program/projects/1).

Next step would be to provide [an outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) so that our editorial team can have a look at it and give guidance!

Thanks Carolyn!

**Comment by robertsvensson** [comment]
Note to self: feature image ordered

**Comment by bradsoo** [comment]
Hey @carolstran I'll be taking over as editor for your piece. I heard earlier last month that your schedule was going to be packed - any chance you managed to find some time to work on this yet? I'm ready when you are and I look forward to hearing from you. Thanks!

**Comment by carolstran** [comment]
Hey @bradsoo! Good to hear from you. To be honest, this totally fell off my plat. I lost focus on a direction (talked to Robert a bit about it, but not so sure that's the way to go now...). Can I email you to run some ideas by you?

**Comment by bradsoo** [comment]
Hi @carolstran, sure! Send them my way: brad -dot- soo.

**Comment by stefanjudis** [comment]
@carolstran Wanna still do this? :) If not we could also close the issue. :)

**Comment by carolstran** [comment]
Shoot sorry yeah @stefanjudis! Totally spaced on emailing @bradsoo 😩 Will make sure to do that this week 👌

**Comment by stefanjudis** [comment]
Hey @carolstran, a kind reminder – can I help with anything here? :)

**Comment by bradsoo** [comment]
@Shy I've followed up on this article idea on Carolyn. I hope to work with @carolstran to get this written and published as soon as possible.

**Comment by carolstran** [comment]
Hey @Shy and @bradsoo, as much as I would love to contribute - I think we just missed the boat on this topic. I'm working on some GraphQL projects, so if anything comes of those I'll open another issue. Thanks for understanding!

**Comment by Shy** [comment]
No worries. Thanks for the heads up.
