### ISSUE TITLE
Article suggestion: WebP, Source Sets & Images API

### ISSUE THREAD

**Issue by teemutammela** [contentful/contribution-program#50]
Hi, I'm planning to create an article about the following topics.

- Introduction of WebP format and advantages over other image formats.
- Creating JPEG fallback for browsers that don't support WebP using source sets.
- Using source sets to show optimized image dimenions and/or compression sizes for different deviced (e.g. mobile, desktop).
- Using asset localization for loading different versions of the image, using title and description as metadata.
- Using cropping/padding tools to create images of different size for meta tags (Twitter Card, Open Graph).

**Comment by Shy** [comment]
Hey @teemutammela, glad to see that you opened up the issue! Sorry on my slow response. I was out on vacation for the last few days. 

Would you be able to create a small [outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) so we can give you feedback before you start writing?

**Comment by Shy** [comment]
@teemutammela wanted to check in and see if you had any questions for us?

**Comment by teemutammela** [comment]
Hi @Shy. Sorry for the late response. No questions at this time, I've been a bit busy with other things, so the writing has been on hold.

**Comment by teemutammela** [comment]
Hi @Shy, here it the preliminary outline you asked for.

- Intro
- WebP
     - Overview of the current image formats
    - Comparison and advantages WebP vs. JPEG and other formats
- Source Sets
    - What are source sets?
    - How to use source sets?
- Images API
    - Overview of the exceptional advantages of the Images API
    - Real-world use cases and examples of using various features of the Images API
- Summary

**Comment by Liz0** [comment]
Hey @teemutammela , thanks so much! The structure looks great. Could you flesh it out with a little more detail?

Thanks!!

**Comment by teemutammela** [comment]
Hi @Liz0 and sorry for the delayed response. Due to the rather non-linear way my brain works, the _"flesh it out with a little more detail"_ part turned out to be a bit challenging for me, so I just finished the whole article. :)

I ended up scrapping some of the topics we originally planned with @Shy, as I felt the article was getting quite lengthy as it is. However, feel free to make editorial changes as you deem necessary. 

https://www.evernote.com/l/AQ1GYNWips1Gm5sCG69oI2iIyacnb9M9EtE

PS: As I have contributed to the Contentful blog in the past, I probably already have an existing bio. When moving forward, please update my bio as it is in the provided article.

**Comment by Liz0** [comment]
Hey no worries!! I'm pretty nonlinear myself ;) 

Thanks for sending the draft, we'll get back to you with edits soon! And I'll make sure to update your bio, no problem.

**Comment by teemutammela** [comment]
Cool, thanks @Liz0.

**Comment by Shy** [comment]
This article is really well written. I honestly only have some super minor optional comments.

In the WebP section you could add a practical example of what the file size reduction looks like going from JPEG to WebP. We'd be happy to include both of those images in the blog too so you could share that it doesn't have a quality impact either.  

Liz is going to take a look, but from my end I'm 👍🏿 on publishing this.

**Comment by teemutammela** [comment]
Thanks, I'm glad you liked it. By all means feel free to add practical examples. I was actually expecting that suggestion, but since I didn't have the technical details how you usually handle file attachments etc. in the blog articles, I thought it best to leave it up to you.

**Comment by teemutammela** [comment]
Here are two sample images where the JPEG artefacts are really noticeable compared to WebP. The original image is an 900x900 PNG, both compressed with 70% quality. The artwork is made by me, so no copyright infringement. :)

WebP: https://images.ctfassets.net/8447ijx3djn4/68gLXgZKkb1G4cSofewsPd/2a091db21a8686917fa0b5f2a841258c/kickin_it_old_school.png?w=450&h=450&fm=webp&q=70

JPEG: https://images.ctfassets.net/8447ijx3djn4/68gLXgZKkb1G4cSofewsPd/2a091db21a8686917fa0b5f2a841258c/kickin_it_old_school.png?w=450&h=450&fm=jpg&q=70

**Comment by Shy** [comment]
We just published the post! https://www.contentful.com/blog/2019/10/31/webp-source-sets-images-api/ 👯‍♂️🎈

I'm going to email you separately to sort out sending you swag and the amazon gift card. Let me know if we need to change or adjust anything.

**Comment by teemutammela** [comment]
Excellent! Everything looks good, thanks @Shy.
