### ISSUE TITLE
Article Submission: Keeping data models simpler, more reusable, and powerful

### ISSUE THREAD

**Issue by allanwhite** [contentful/contribution-program#51]
I dusted off #11 and rewrote it some, published it here: 

https://dev.to/allanwhite/it-s-all-about-relationships-keeping-data-models-simpler-more-reusable-and-powerful-257o

It's basically the same structure. If you'd like to syndicate it or republish it, let's talk.

**Comment by Shy** [comment]
Hey Allan,

This is great. I really like this article. I'm looping in Liz who can help migrate it from Dev over to the contentful blog.

**Comment by allanwhite** [comment]
@Shy @Liz0 I can provide the raw markdown and original image assets if that's helpful.

**Comment by Liz0** [comment]
Yes please do! I had a look at it, and I think it's pretty much good to go! I would maybe do some very minor edits around naming conventions of our features and maybe a bit more internal linking if that's fine for you. 

MD file and images would be great!

**Comment by Shy** [comment]
Hey @allanwhite Just wanted to bump you on sending the markdown and images over. Feel free to shoot me an email if that's easier than GitHub. I'm shy@Contentful.com

**Comment by allanwhite** [comment]
@shy missed your notifs, here you go! 

### Image assets

![blog-relationships-data-modeling](https://user-images.githubusercontent.com/887931/67595918-82603980-f71c-11e9-8098-6d7345bd4c68.jpg)

![blog-relationships-data-modeling-breakdown](https://user-images.githubusercontent.com/887931/67595604-eafae680-f71b-11e9-8bf1-48cd96e85fcf.jpg)

![datica blog screenshot](https://user-images.githubusercontent.com/887931/67595606-eafae680-f71b-11e9-909b-e9c802e1f7be.png)

### Article raw markdown

@Liz0 
[Keeping data models simpler, more reusable, and powerful.md.txt](https://github.com/contentful/contribution-program/files/3773319/Keeping.data.models.simpler.more.reusable.and.powerful.md.txt)

**Comment by Liz0** [comment]
Hey Alan! Thank you so much and sorry for the wait, I was on holiday for a few days. I'll get to editing this tomorrow!

**Comment by Liz0** [comment]
Hey Allan, I did some very light editing on this mostly for specific terms we use to refer to our product features. I've requested a header from our design team and will check when we can slot it in on our editorial calendar. I'll keep you in the loop!

**Comment by Liz0** [comment]
Hey Allan, this is scheduled to go up next week, we have a bit of a backlog on blog posts to be published at the moment. Thank you for your patience!

**Comment by Liz0** [comment]
Hi  Allan, I'm queueing this up for tomorrow -- would you like me to use your github profile description for your bio, or the one from the blog that this post was originally published on?

**Comment by Shy** [comment]
The article is up! Check it out here: https://www.contentful.com/blog/2019/11/19/keeping-content-models-simpler-reusable-powerful/
