### ISSUE TITLE
Article: Creating an automated slug with contentful

### ISSUE THREAD

**Issue by azer53** [contentful/contribution-program#52]
Hi!

Liz and Shy contacted me regarding an article on my personal blog.
If you can, you can review and give some feedback. Would love some tips.
Feel free to reach out with questions or if you need additional information!

Link:
https://ecolpaert.com/creating-an-automated-slug-with-contentful

Kind regards

Eli

**Comment by Shy** [comment]
Hey Eli,

This looks great. Any chance you'd be able to put this in a google doc for us so we can give feedback?

**Comment by azer53** [comment]
Sure, here it is: https://docs.google.com/document/d/12sT9Hw-VXtCjMHxZUppioC1Hvc-TdVSEg-nnLOtxReQ/edit?usp=sharing

**Comment by Liz0** [comment]
Rad, thank you!!

**Comment by azer53** [comment]
Hi, 
Do you have some feedback?
Thanks!

**Comment by Liz0** [comment]
Hey, sorry for the wait! I'm working on a somewhat longer backlog of edits. I'll have a look at it in the next day or so!

**Comment by Liz0** [comment]
Hey Eli, thanks for your patience! I put my edits in as suggestions, all small grammar/punctuation stuff, would be great if you could go through and accept the changes. There was just one bigger change, the intro section to where you start describing how to implement an automated slug in Contentful. It just needs to be adapted considering it's being reposted to our blog, so people already know us ;) 

Thanks again, and let me know if you have any questions / when you've had a chance to do the edit!

**Comment by azer53** [comment]
Thanks for reviewing, great help! I rewrote the requested bigger change. Could you check if this works for you?

**Comment by Liz0** [comment]
Just had another look, thanks for the edit!!! I reworded the first sentence slightly, if it's OK with you it's good to go from my side! Next steps: I request a header from our design team, and queue it up to post. It may take another week or so again since we have a bit of a backlog of posts at the moment and want to space out the community posts :) Thanks for your patience and hard work!!

**Comment by azer53** [comment]
Sure, accepted the changes! Thanks for the collaboration!

**Comment by Shy** [comment]
Published at https://www.contentful.com/blog/2019/11/29/creating-automated-slug-with-contentful/

Thanks so much for working with us on this article!
