### ISSUE TITLE
Dead simple NextJS + contentful for beginners, static or SSR

### ISSUE THREAD

**Issue by ScreamZ** [contentful/contribution-program#54]
Hello, I'm writing an article about NextJS and Contentful, especially for beginner and without too much dependencies that make it hard to understand.

The name of the article is going to be:

`The most simple Contentful + React tutorial using a NextJS application 👊🏻`

« A very simple JAM Stack how-to tutorial to use Contentful and React without having to master +1000 tools as prerequisite.»

I would like to know if this can be part of that contribution part ? As a content you're looking for ?

It's a simple Article-Author listing page, that use SSR or Static rendering to be displayed.
First version is simple as thatn but I plan to extends it a bit if it get successful to explain how to deploy on the cloud. And maybe why not write more articles.

It's a `9 min read (1907 words)` article currently.

----
## But who am I ?

I'm a (new?) Medium writer but also tech-lead @ Kaliop (France), which is partner of Contentful.

Here is my medium stats for current month, if this is something that matters for you. I can bring a "modest" visibility.

![image](https://user-images.githubusercontent.com/6640835/68533646-99fa0d80-032b-11ea-9c67-969b3d3a8525.png)

I'm also **Contentful Certified Professional** since October.

Thanks for your future answer,
Regards,

Andréas

PS: Feel free to reach me on linkedin if you have any questions: https://www.linkedin.com/in/andreas-hanss/

**Comment by ScreamZ** [comment]
@Shy By the time it as been released https://medium.com/javascript-in-plain-english/the-most-simple-contentful-react-tutorial-using-a-nextjs-application-8d0ce4596ad6

Feel free to comment if you've ideas.

Regards

**Comment by Shy** [comment]
Hey Andréas,

Sorry for my slow response. I didn't get a notification until you tagged me. We'd be happy to repost this article. Would you be able to put it in a google doc so we could provide you some small copy edits? 

Best,

Shy

**Comment by ScreamZ** [comment]
@Shy https://docs.google.com/document/d/1kyqvJ0qLC6pii9-NXNMcNpFQkcm0FqNqTNAd1BxKWjA/edit?usp=sharing

**Comment by Shy** [comment]
Awesome. I'm gonna put some comments in this afternoon and Liz is gonna take a look later this week.

**Comment by ScreamZ** [comment]
@Shy Hey, any news ?

**Comment by ScreamZ** [comment]
@Shy hello, did you had time to check my article ? :'(

**Comment by Shy** [comment]
@ScreamZ I'm so sorry I haven't had a chance to take a look at this. I've been a little swamped with the holidays. I'm taking a look right now.
