### ISSUE TITLE
Article Idea: Winning Organic Search using 'Rich Text'

### ISSUE THREAD

**Issue by youmustfight** [contentful/contribution-program#55]
Hey folks! 👋

We've been getting a lot of questions about how our 7-person poverty fighting nonprofit has been beating public companies in organic search. An edge we have is how we're using the Rich Text content type to make our contract writers' content highly optimized for advanced SEO features (ex: structuring both in HTML/JSON+LD to ensure Google identifies a page as a How-To guide)

I thought it'd be nice to write a bit about it so folks in the Contentful community can learn and get some new ideas! For our first 1 1/2 years, I was the designer and the developer and I built a website that gets 1.5 million unique visitors per year. At different points in time we had 7-15 writers on contract during that period.

Open to feedback on the outline but some basics that come to mind now are:

### Outline

1. Background on nonprofit, **why organic traffic was our strategy**, and our stack
2. **What Google's Crawlers Want** - Semantic HTML, Leading Navigation, and JSON+LD
3. Processing Rich Text to do clean `<section />`s
4. Processing Rich Text to automatically create internal page navigation
5. Processing Rich Text to create highly detailed JSON+LD (Ex: FAQ Page JSON+LD)
6. Conclusion - Rich Text is incredibly flexible in transforming normal written content crawlers love. We use it various other ways to also improve CTAs and incorporate programmatically generated content. These are just some ideas of how engineering can empower content creators

Lmk what you think @Shy @Liz0 !!

**Comment by youmustfight** [comment]
WIP: https://docs.google.com/document/d/1sl_iM7QUdWpS5hkzO3AYRIPCuJvySZxut54OS74qxpU/edit?usp=sharing

**Comment by Shy** [comment]
Thanks for posting this. It looks great. Sorry for my slow response, you're post came in while we were out on Holiday Break. I've bumped the status to in progress. Let me know when you're ready to move into the review stage.

**Comment by Shy** [comment]
Just heard that you had a call with Kiersten from our team and the article is ready to review. I'm updating the ticket status to help track it.

**Comment by Shy** [comment]
Closing this issue since the article is published (https://www.contentful.com/blog/2020/01/13/winning-organic-search-with-rich-text/). Feel free to shoot me an email (Shy @ Contentful) so I can sort out hooking you up with an Amazon Gift Card as a thank you for working with us!
