### ISSUE TITLE
Article: Automatically importing your assets from AWS S3 to Contentful with the Serverless Framework

### ISSUE THREAD

**Issue by eahefnawy** [contentful/contribution-program#58]
@Shy @stefanjudis I think this article would be really helpful especially for users trying to migrate to Contentful from legacy systems that uses S3, or folks that actively use S3 with their application, but need to keep it in sync with Contentful for publishing.

I don't have an outline yet, but in a nutshell, I'll be using the Serverless Framework to subscribe to s3 events, so that each file uploaded to S3 would automatically trigger an AWS Lambda function that uploads this file to Contentful using the Mangement API.

What do you guys think? Would you be interested in this article?

**Comment by Shy** [comment]
Hey @eahefnawy, we try to space out working with the same author so we can see how an article turns out before starting to work on a second post. I'd be happy to chat about this once we get your first post has had a chance to get up on the Contentful site.

**Comment by eahefnawy** [comment]
Ok, in that case, I'm looking forward to your feedback on the first article. I already sent the draft.

**Comment by Shy** [comment]
Hey Max,

Thanks for submitting this. We've actually decide that we're going to be pausing the contribution program going forward. If you do decide to write this article, let me know (shy@contentful.com) and I'd be happy to send you some swag and get the word about it.

Shy
