### ISSUE TITLE
Author Wanted: serverless framework, claudia.js, ... what's the silver bullet?

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contribution-program#6]

**Comment by allanwhite** [comment]
I really liked your [post](https://www.contentful.com/blog/2018/04/11/new-era-static-sites-rise-future/) from the other day, I've been keen to learn Vue as a way to either build the next version of our site, or at the least, power some more flexible list views for our site (that need more dynamic input than a static site alone). Internal tools (like a customer dashboard or sales tool that integrates other data sources) is one I think of Vue being a good fit for. 

I'd really like to see how the server-side rendering might solve SEO problems posed by SPAs (where a spider is actually looking for prerendered pages).

**Comment by stefanjudis** [comment]
> I'd really like to see how the server-side rendering might solve SEO problems posed by SPAs (where a spider is actually looking for prerendered pages). Agree – that could be nice.

It be its own article then, though. This issue here, is more about serverless frameworks that help dealing with lambda and such. :)
