### ISSUE TITLE
Article Idea: Using the Python Contentful Management API to Simplify the Content Publishing Process

### ISSUE THREAD

**Issue by maxemitchell** [contentful/contribution-program#60]
Hey everyone!

I recently wrote a short [python script](https://github.com/maxemitchell/photo_manager) that uploads a folder of images to both Google Drive and Contentful, and I think it would be a great addition to write an article focusing on the Contentful portion. I also made this [video](https://www.youtube.com/watch?v=CMcOuXH0hck) going over the creation process, but I keep it at a less technical level than I would for this article.

The article would be targeted towards those using Contentful in a photography portfolio capacity, and would walk the reader through creating a script that uploads the images, processes them, and publishes them before adding them to a "photo collection" content entry. This personally saved me a lot of time not having to individually upload and publish each image, and I'm sure there are other people with a similar workflow who it would help.
#
Please let me know what you think! :)

Thanks,
Max

**Comment by Shy** [comment]
Hey Max,

Thanks for submitting this. We've actually decide that we're going to be pausing the contribution program going forward. If you do decide to write this article, let me know (shy@contentful.com) and I'd be happy to send you some swag and get the word about it.

Shy
