### ISSUE TITLE
The rise of headless CMS

### ISSUE THREAD

**Issue by HoverBaum** [contentful/contribution-program#7]
I would like to talk about benefits of headless CMS over traditional systems such as Wordpress or Drupal.

I picture going through some personal experiences as a developer and also exploring business benefits and concerns in regards to going headless.

**Comment by stefanjudis** [comment]
@HoverBaum That sounds great!

**Comment by HoverBaum** [comment]
Did a gist: https://gist.github.com/HoverBaum/ec9e8290218834420773be3b28829c2b

Actually have a rough first draft of this from which I extracted the outline. Might be getting this backwards a bit. Haven't really taken that much of a structured approach with posting before.

**Comment by stefanjudis** [comment]
Hey Hendrik,

when you have a draft of this already, I guess, then we can skip the outline part and you could share the draft with me and I'll introduce our editorial team. :) 

A google doc would be great - as it's the best way to collaborate. Then you could share it with me `stefan.judis@contentful.com` and we could start having a look at it. :)

**Comment by HoverBaum** [comment]
Shared it with you @stefanjudis, really just a first draft though 😉

**Comment by stefanjudis** [comment]
@HoverBaum It looks promising. :) Made a bunch of comments.

Thanks a lot for this!

**Comment by HoverBaum** [comment]
Thanks for the input 👍 

I will work through it next week.

**Comment by robertsvensson** [comment]
Hi @HoverBaum 
I'm Robert, Technical Writer for Contentful, and I'll be your editor for this project.

Your draft already looks great and I left a few comments in the gdoc for you to consider.

**Comment by robertsvensson** [comment]
@HoverBaum Could you give me editing rights to the gdoc and I'll take it into editing mode?

**Comment by robertsvensson** [comment]
Note to self: feature image ordered MD-93

**Comment by HoverBaum** [comment]
@robertsvensson granted you access.

**Comment by robertsvensson** [comment]
@HoverBaum I've made my round of editing. Read it through and let me know if you think it's good enough to be published.

**Comment by robertsvensson** [comment]
@HoverBaum Your suggestion looks good to me. 

The next step is for me to move the gdoc content into our preview environment. I will e-mail you a link once that's done.

**Comment by stefanjudis** [comment]
Cleanup time. :) This was published. 🎉
