### ISSUE TITLE
Building a multi-lingual website with Contentful and NextJS

### ISSUE THREAD

**Issue by connor-baer** [contentful/contribution-program#8]
[SumUp](https://sumup.com) recently launched a new modular website serving 32 countries in 36 languages. In a talk at the Contentful Meetup Berlin, I shared how we leverage the flexibility of Contentful to build a highly modular content structure, dove into the challenges we faced with localization, and shared lessons learned while optimizing the website for performance. Here's the recording for reference: https://www.youtube.com/watch?v=urd_t807APg

I'd like to turn the talk into a case-study-style blog post, updated with the improvements we've made since I gave the talk.

**Comment by stefanjudis** [comment]
That sounds great @connor-baer! I already enjoyed the talk and would love to see it written down. :)

**Comment by stefanjudis** [comment]
If you could provide us [a quick outline](https://github.com/contentful/contribution-program/blob/master/OUTLINE.md) that'd be great. 😊 

Can be quick though, as we've seen the talk already. :)

**Comment by connor-baer** [comment]
- [ ] Building a dynamic, multilingual website
- [ ] What you will learn today
- [ ] Prerequisites
- [ ] A new website for SumUp
  - [ ] Our previous tech stack (and its pains)
  - [ ] New requirements: modular + scalable
- [ ] Contentful + NextJS save the day
  - [ ] Content structure
    - [ ] 32 countries — one space
    - [ ] Every page is a route
    - [ ] Sharing data between pages
  - [ ] Localisation
    - [ ] To fall back or not to fall back
    - [ ] Custom localisation + mapping
    - [ ] UI extensions make life easier
  - [ ] Performance
    - [ ] Cache, cache, cache
    - [ ] SSR with NextJS
- [ ] Summary
  - [ ] Did we meet our requirements?
  - [ ] Outlook

You can follow my progress here: https://paper.dropbox.com/doc/Building-a-multilingual-website-with-Contentful-and-NextJS-Jz54jGDchLM6oPbkb5ZPK#:uid=552950024072666944686713&h2=Outline

**Comment by stefanjudis** [comment]
@connor-baer Do we want to move that over the finish line? :) 
Can I help with anything?

**Comment by connor-baer** [comment]
I have two weeks of vacation at the beginning of September, a perfect time to finish this. Thanks for the reminder!

**Comment by stefanjudis** [comment]
Hello hello, how's the vacation going? :)

**Comment by stefanjudis** [comment]
Hey @connor-baer I'm closing this for now. :) Happy to re-open in the future. :)

**Comment by connor-baer** [comment]
@stefanjudis Yeah, I think the topic is outdated anyway. Lemme try to come up with a different topic :)

**Comment by stefanjudis** [comment]
👍

**Comment by matyushen** [comment]
@connor-baer Nice talk, thank you! Have you managed to finish this case-study-blog-post thing? Would love to hear in more details about how you deal with i18n in contentful + react/next.

**Comment by connor-baer** [comment]
Hi @matyushen, thank you! No, I didn't end up writing the blog post. I can give you a brief summary on how we deal with internationalization though. 

Essentially, localization happens only on the server. We run a small Node backend which...

1. proxies our Contentful API calls
2. caches the data in redis (so we're resilient to Contentful downtimes)
3. picks the right translation for the current locale (based on the hostname, e.g. `sumup.de` -> `de-DE`) 
4. and formats data such as dates and currencies in the local format.

The frontend simply calls the page endpoint in [`getInitialProps`](https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle) and receives the already localized content. Hint, you can prefix any pathname on a SumUp website with `/api/v2` to see the data, e.g. https://sumup.com/api/v2/about/.

Does that help?

**Comment by matyushen** [comment]
Hey @connor-baer, thanks for the answer! Very interesting. Are you using Contentful's GraphQL API? We were using CDA mapping all content models to our own GraphQl API. But it quickly became a pain to maintain (especially with reference fields and unions), so we switched to GraphQL API merging the remote schema and basically talking to it directly from the client. But the problem I encountered is that all Contentful fields in the schema except `sys` are nullable. Have you had this problem?

**Comment by connor-baer** [comment]
We're not using the GraphQL API yet, though we might explore it in the future. It could solve some of our current pain points since what we do on our server is similar in principle to what GraphQL does. 

We had some problems when switching to Contentful early on when data would be unexpectedly `undefined` or `null`. We overcame those problems with more resilient programming where we don't rely on any data being present.

**Comment by matyushen** [comment]
Resilient programming sounds like a good approach. Thank you!
